Repository ansible-collections/community.vmware, pull requests merged in 2020-10, with the labels that each got.

#414 Fix issue with duplicate custom attribute names
  changelogs/fragments/412-vmware_guest_custom_attributes.yml
  plugins/modules/vmware_guest_custom_attributes.py
Labels: gate, has_issue

#384 vmware_guest: fix issue of checking specified hardware version when disk controller is nvme
  changelogs/fragments/381-vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: gate

#411 vmware_guest_video: Gather facts for poweredoff VM
  changelogs/fragments/408_video_facts.yml
  plugins/modules/vmware_guest_video.py
Labels: gate, has_issue

#418 vmware_guest_sendkey: Add sleep_time parameter
  changelogs/fragments/404_vmware_guest_sendkey.yml
  plugins/modules/vmware_guest_sendkey.py
Labels: gate, has_issue

#422 Update community.vmware.vmware_object_role_permission_module.rst
  docs/community.vmware.vmware_object_role_permission_module.rst
Labels: docs

#372 vca_*: use relative doc fragment name
  plugins/modules/vca_fw.py
  plugins/modules/vca_nat.py
Labels: gate

#427 vmware_object_role_permission: Missing required parameters in examples
  changelogs/fragments/426_vmware_object_role_permission.yml
  plugins/modules/vmware_object_role_permission.py
Labels: docs, gate, has_issue

#450 vmware_vm_vm_drs_rule: report changes in check mode
  changelogs/fragments/440_vmware_drs_rule.yml
  plugins/modules/vmware_vm_vm_drs_rule.py
  tests/integration/targets/vmware_vm_vm_drs_rule/tasks/main.yml
Labels: gate, has_issue

#439 vmware_tag_manager: Add new parameter 'moid'
  changelogs/fragments/430_vmware_tag_manager.yml
  plugins/modules/vmware_folder_info.py
  plugins/modules/vmware_tag_manager.py
  plugins/modules/vmware_vm_info.py
  tests/integration/targets/vmware_folder_info/tasks/main.yml
  tests/integration/targets/vmware_tag_manager/tasks/main.yml
  tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
Labels: gate, has_issue

#461 vmware_resource_pool: Add new allocation shares options for cpu and memory
  changelogs/fragments/461_vmware_resource_pool.yml
  plugins/modules/vmware_resource_pool.py
  tests/integration/targets/vmware_resource_pool/tasks/main.yml
Labels: gate, has_issue

#463 vmware_guest_info: Add a new parameter to gather tag info
  changelogs/fragments/vmware_guest_info.yml
  plugins/modules/vmware_guest_info.py
  tests/integration/targets/vmware_tag/tasks/tag_manager_ops.yml
Labels: feature, gate
