Repository ansible-collections/community.vmware, pull requests merged in 2020-11, with the labels that each got.

#455 vmware_cluster_info: Return tag information
  changelogs/fragments/453_vmware_cluster_info.yml
  plugins/module_utils/vmware_rest_client.py
  plugins/modules/vmware_cluster_info.py
  tests/integration/targets/vmware_cluster_info/tasks/main.yml
Labels: gate, has_issue

#469 vmware_resource_pool: add a config changing feature
  changelogs/fragments/469_vmware_resource_pool.yml
  plugins/modules/vmware_resource_pool.py
  tests/integration/targets/vmware_resource_pool/aliases
  tests/integration/targets/vmware_resource_pool/tasks/main.yml
Labels: gate

#460 Fix the special characters aren't decoded by the find_obj method
  changelogs/fragments/460_module_utils_vmware.yml
  plugins/module_utils/vmware.py
  tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
  tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
Labels: gate

#466 vmware_deploy_ovf: support for networks with the same names in different datacenters
  changelogs/fragments/vmware_deploy_ovf.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_deploy_ovf.py
Labels: gate, has_issue

#425 vmware_vm_inventory: Add support for category
  changelogs/fragments/350_vmware_vm_inventory.yml
  plugins/inventory/vmware_vm_inventory.py
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
Labels: feature, gate, has_issue

#441 vmware_vm_inventory: Improve plugin performance
  changelogs/fragments/441_vmware_vm_inventory_performance.yaml
  plugins/inventory/vmware_vm_inventory.py
Labels: gate, has_issue, performance

#474 Enable support for vds 7 in vmware_dvswitch
  changelogs/fragments/474_vmware_dvswitch.yml
  plugins/modules/vmware_dvswitch.py
Labels: feature, gate

#465 vmware_category: Add addition associable types
  changelogs/fragments/454_vmware_category.yml
  plugins/modules/vmware_category.py
Labels: gate

#482 vmware_resource_pool: fix a bug that always updates the resource pool config
  changelogs/fragments/482_vmware_resource_pool.yml
  plugins/modules/vmware_resource_pool.py
Labels: gate

#480 vmware_host_scsidisk_info: new module
  README.md
  docs/community.vmware.vmware_host_scsidisk_info_module.rst
  plugins/modules/vmware_host_scsidisk_info.py
  tests/integration/targets/vmware_host_scsidisk_info/aliases
  tests/integration/targets/vmware_host_scsidisk_info/tasks/main.yml
Labels: gate, new_module_request

#489 vmware_vm_inventory: Ensure self.port is integer
  changelogs/fragments/489_vmware_vm_inventory_port_cast_integer.yaml
  plugins/inventory/vmware_vm_inventory.py
Labels: gate, has_issue

#495 Disable Category test for cluster
  plugins/modules/vmware_category.py
  tests/integration/targets/vmware_cluster_info/tasks/main.yml
Labels: gate

#477 vmware_cluster_ha: Add APD and PDL configuration
  changelogs/fragments/451_vmware_cluster_ha.yml
  plugins/modules/vmware_cluster_ha.py
  tests/integration/targets/vmware_cluster_ha/tasks/main.yml
Labels: gate, has_issue

#499 vmware_deploy_ovf: Fix the issue that the name variable referenced error occurs
  changelogs/fragments/499-vmware_deploy_ovf.yml
  plugins/modules/vmware_deploy_ovf.py
Labels: gate, has_issue

#505 vmware_vm_inventory: Skip inaccessible VM configuration
  changelogs/fragments/inventory_fix.yml
  plugins/inventory/vmware_vm_inventory.py
Labels: gate, has_issue

#486 vmware_guest_controller: Add error handling
  changelogs/fragments/vmware_guest_ctrl.yml
  plugins/modules/vmware_guest_controller.py
Labels: bug, gate

#475 vmware_drs_group: code refactor
  changelogs/fragments/81_vmware_drs_group.yml
  plugins/modules/vmware_drs_group.py
Labels: feature_request, gate, has_issue

#510 vmware_guest: Document networks connected and start_connected sub-options
  changelogs/fragments/507-vmware_guest_fix-documentation.yml
  plugins/modules/vmware_guest.py
Labels: documentation, gate, has_issue

#520 Shorten URL for vApp Properties
  docs/community.vmware.vmware_guest_module.rst
  plugins/modules/vmware_guest.py
Labels: gate

#524 vmware_resource_pool: Manage resource pools on ESXi hosts
  changelogs/fragments/492-vmware_resource_pool-esxi_host.yml
  plugins/modules/vmware_resource_pool.py
Labels: feature, gate, has_issue

#515 vmware_content_deploy_ovf_template: Add content_library parameter
  changelogs/fragments/514_vmware_content_deploy_ovf_template-add_content_library_parameter.yml
  plugins/modules/vmware_content_deploy_ovf_template.py
Labels: feature_request, gate, has_issue
