Repository ansible-collections/community.vmware, pull requests merged in 2020-05, with the labels that each got.

#46 New module for Vcenter infra profile config operations
  changelogs/fragments/46-Vcenter-infra-profile-config-operations.yml
  plugins/modules/vmware_vc_infraprofile_info.py
  tests/integration/targets/vmware_vc_infraprofile_info/aliases
  tests/integration/targets/vmware_vc_infraprofile_info/tasks/main.yml
Labels: gate

#65 VMware: add SATA cdrom support in vmware_guest module
  changelogs/fragments/65-vmware_guest.yml
  plugins/modules/vmware_guest.py
  tests/integration/targets/vmware_guest/tasks/cdrom_d1_c1_f0.yml
  tests/integration/targets/vmware_guest/tasks/cdrom_d1_c1_f1.yml
Labels: gate

#29 Add check mode, diff and some new functionality to vmware_guest_network
  changelogs/fragments/66922-vmware_guest_network.yml
  plugins/modules/vmware_guest_network.py
  tests/integration/targets/vmware_guest_network/tasks/main.yml
Labels: bug, gate

#109 VMware: add new vmware module vmware_host_logbundle
  changelogs/fragments/109-vmware_host_logbundle.yml
  plugins/modules/vmware_host_logbundle.py
  tests/integration/targets/vmware_host_logbundle/aliases
  tests/integration/targets/vmware_host_logbundle/tasks/main.yml
Labels: gate

#110 VMware: add new vmware module vmware_host_logbundle_info
  changelogs/fragments/110-vmware_host_logbundle_info.yml
  plugins/modules/vmware_host_logbundle_info.py
  tests/integration/targets/vmware_host_logbundle_info/aliases
  tests/integration/targets/vmware_host_logbundle_info/tasks/main.yml
Labels: gate

#141 Correct the set fact to fit the return structure
  changelogs/fragments/141_Correct_doc_of_vmware_local_role_info
  plugins/modules/vmware_local_role_info.py
Labels: gate

#194 galaxy: ensure the import works
  galaxy.yml
  plugins/modules/vmware_content_deploy_ovf_template.py
  plugins/modules/vmware_export_ovf.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_network.py
  plugins/modules/vmware_guest_tools_upgrade.py
Labels: CI, gate

#181 Remove unnecessary unit test requirements
  tests/unit/requirements.txt
Labels: gate

#132 Revert "req: pyvmomi < 7.0 (#122)"
  requirements.txt
Labels: gate

#155 Update README for requirements
  README.md
  changelogs/fragments/154_update_doc.yml
Labels: gate

#198 inventory_vmware_vm_inventory test - Remove exit code from trap
  tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
Labels: gate

#195 Fix vmware docs
  plugins/modules/vmware_vc_infraprofile_info.py
Labels: gate

#138 add functional test for vcenter_extension_info
  tests/integration/targets/vcenter_extension_info/aliases
  tests/integration/targets/vcenter_extension_info/meta/main.yml
  tests/integration/targets/vcenter_extension_info/tasks/main.yml
Labels: gate

#188 specify the name of the content library from where the template needs…
  changelogs/fragments/188-vmware_content_deploy_template-specify_content_library_name.yml
  plugins/module_utils/vmware_rest_client.py
  plugins/modules/vmware_content_deploy_template.py
Labels: gate

#136 add storage_provisioning type into vmware_content_deploy_ovf_template.
  changelogs/fragments/vmware_content_deploy_ovf_template_add_storage_provision_type.yml
  plugins/modules/vmware_content_deploy_ovf_template.py
Labels: gate

#208 vmware_host_facts: Handle exception in fact gathering
  changelogs/fragments/183_vmware_host_facts.yml
  plugins/modules/vmware_host_facts.py
Labels: gate

#166 VMware: add vm existence check processing to vmware_deploy_ovf module
  changelogs/fragments/166-vmware_deploy_ovf.yml
  plugins/modules/vmware_deploy_ovf.py
Labels: gate

#177 Update boilerplate and future-import
  plugins/connection/vmware_tools.py
  plugins/doc_fragments/vca.py
  plugins/doc_fragments/vmware_rest_client.py
  tests/sanity/ignore-2.10.txt
  tests/unit/mock/path.py
  tests/unit/mock/vault_helper.py
  tests/unit/mock/yaml_helper.py
  tests/unit/module_utils/conftest.py
  tests/unit/modules/conftest.py
  tests/unit/modules/utils.py
Labels: gate

#201 vmware_guest: add support for SATA and NVME disk controller types
  changelogs/fragments/44957-vmware_guest.yml
  plugins/modules/vmware_guest.py
  tests/integration/targets/vmware_guest/tasks/multiple_disk_controllers_d1_c1_f0.yml
Labels: gate

#186 Made vmnics attribute optional for DVS creation
  changelogs/185-make_vnics_optional_for_dvs.yml
  plugins/modules/vmware_dvs_host.py
  tests/integration/targets/vmware_dvs_host/aliases
  tests/integration/targets/vmware_dvs_host/tasks/main.yml
Labels: gate

#202 vmware_vm_inventory: Handle binary data in VM properties
  changelogs/fragments/7052_awx_handle_binary.yml
  plugins/inventory/vmware_vm_inventory.py
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
Labels: gate
