Repository ansible-collections/community.vmware, pull requests merged in 2020-09, with the labels that each got.

#374 pylint: ensure the check pass
  plugins/inventory/vmware_vm_inventory.py
  scripts/inventory/vmware.py
  scripts/inventory/vmware_inventory.py
Labels: gate

#376 vmware_cluster: Don't ignore vim.fault.DuplicateName exception
  plugins/modules/vmware_cluster.py
Labels: gate

#366 Fix issue of the vmware_cluster_info module does not decode of a clus…
  changelogs/fragments/366-vmware_cluster_info.yml
  plugins/modules/vmware_cluster_info.py
  tests/integration/targets/vmware_cluster_info/tasks/main.yml
Labels: affects_2.10, bug, cloud, community_review, gate, has_issue, integration, module, needs_ci, needs_triage, plugins, stale_ci, tests

#382 add an example of host filter with OR conditions in vmware inventory plugin
  plugins/inventory/vmware_vm_inventory.py
Labels: gate

#380 Support special characters in an object name
  changelogs/fragments/380-vmware-handle-special-characters.yml
  plugins/module_utils/vmware.py
  tests/integration/targets/vmware_cluster/tasks/main.yml
  tests/integration/targets/vmware_datacenter/tasks/main.yml
  tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
  tests/integration/targets/vmware_dvswitch/tasks/main.yml
  tests/integration/targets/vmware_guest/defaults/main.yml
  tests/integration/targets/vmware_guest/tasks/create_vm_using_special_characters.yml
  tests/integration/targets/vmware_portgroup/tasks/main.yml
  tests/integration/targets/vmware_vswitch/tasks/main.yml
Labels: gate

#387 vmware_vm_inventory: correct docs for requirements
  changelogs/fragments/vmware_vm_inventory_req.yml
  plugins/inventory/vmware_vm_inventory.py
Labels: gate

#368 Fix to split the variables setting process by determining whether it …
  changelogs/fragments/368-vmware_guest_customization_info.yml
  plugins/modules/vmware_guest_customization_info.py
Labels: gate

#388 add a host filter example with regex
  plugins/inventory/vmware_vm_inventory.py
Labels: gate

#383 Ignore leading and trailing whitespace when searching for objects
  changelogs/fragments/335-vmware-strip-names-when-searching.yml
  plugins/module_utils/vmware.py
Labels: gate

#371 tox: add add_docs environment
  README.md
  tox.ini
Labels: action, gate

#400 Ensure that VM are created on the requested ESXi host
  changelogs/fragments/400-vm-created-on-specified-host.yml
  plugins/modules/vmware_guest.py
Labels: gate

#406 vmware_guest_info: Fix get tags API call
  changelogs/fragments/403_fix_vmware_guest_info.yml
  plugins/modules/vmware_guest_info.py
  tests/integration/targets/vmware_tag/tasks/tag_manager_ops.yml
Labels: gate, has_issue

#402 add a new module vmware_host_iscsi_info
  changelogs/fragments/402-vmware_host_iscsi_info.yml
  plugins/modules/vmware_host_iscsi_info.py
  tests/integration/targets/vmware_host_iscsi_info/aliases
  tests/integration/targets/vmware_host_iscsi_info/tasks/iscsi_info_module_test_tasks.yml
  tests/integration/targets/vmware_host_iscsi_info/tasks/main.yml
Labels: gate, new_module

#401 vmware_guest_network: Fix to port group changes to work properly
  changelogs/fragments/401-vmware_guest_network.yml
  plugins/modules/vmware_guest_network.py
  tests/integration/targets/vmware_guest_network/tasks/main.yml
Labels: gate, has_issue
