Repository ansible-collections/community.vmware, pull requests merged in 2020-08, with the labels that each got.

#329 Add BOTMETA and .github folder
  .github/BOTMETA.yml
  .github/settings.yml
Labels: gate

#317 vmware_guest: Deprecate CDROM config as dict
  changelogs/fragments/cdrom_dict_removal.yml
  plugins/modules/vmware_guest.py
Labels: gate

#330 prepare 1.1.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/124-vmware-migrate-vmk-to-std-switch.yaml
  changelogs/fragments/182_content_library.yml
  changelogs/fragments/224-vmware_host_iscsi.yml
  changelogs/fragments/243_vmware_guest_snapshot_info.yml
  changelogs/fragments/269_vmware_vm_inventory.yml
  changelogs/fragments/274_vmware_guest.yml
  changelogs/fragments/275_vmware_vcenter_settings_info.yml
  changelogs/fragments/287_deploy_ovf_template.yml
  changelogs/fragments/321-vmware_cluster_info.yml
  changelogs/fragments/52-vmware_dvs_portgroup_find_fix.yml
  changelogs/fragments/porting-guide.yml
  changelogs/fragments/pvlan-config-vmware-dvs-portgroup.yml
  changelogs/fragments/vca_deprecate.yml
  changelogs/fragments/vmware_pg_options.yml
  changelogs/fragments/vmware_vm_storage_policy_module.yml
Labels: gate

#319 add an integration test for the vmware_migrate_vmk module
  tests/integration/targets/vmware_migrate_vmk/aliases
  tests/integration/targets/vmware_migrate_vmk/tasks/main.yml
Labels: gate

#259 doc: explain how to push a release
  README.md
Labels: gate

#289 Add advanced options to vmware_cluster_vsan
  changelogs/fragments/260-vmware_cluster_vsan.yml
  plugins/modules/vmware_cluster_vsan.py
  tests/integration/targets/vmware_cluster_vsan/aliases
  tests/integration/targets/vmware_cluster_vsan/tasks/main.yml
Labels: gate

#331 Fix connection plugin macro in BOTMETA
  .github/BOTMETA.yml
Labels: gate

#332 vmware_cluster_ha: Truthy strings as strings instead of booleans
  changelogs/fragments/286-vmware_cluster_ha.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_cluster_ha.py
  tests/integration/targets/vmware_cluster_ha/tasks/main.yml
  tests/integration/targets/vmware_host_config_manager/tasks/main.yml
Labels: affects_2.10, bug, community_review, gate, has_issue, integration, module, module_utils, needs_ci, stale_ci, tests

#364 Fix Repl and Repl_NFC detection
  changelogs/fragments/364-vmware_vmkernel-replciation-fix.yml
  plugins/modules/vmware_vmkernel.py
Labels: affects_2.10, bug, community_review, gate, module, needs_ci, new_contributor, small_patch, stale_ci

#358 Fix vmware_guest_serial_port to have idempotency
  changelogs/fragments/358-vmware_guest_serial_port.yml
  plugins/modules/vmware_guest_serial_port.py
  tests/integration/targets/vmware_guest_serial_port/tasks/main.yml
Labels: affects_2.10, bug, community_review, gate, has_issue, integration, module, needs_ci, stale_ci, tests

#354 vmware_content_deploy_ovf_template - requires the resource_pool param
  changelogs/fragments/163-vmware_content_deploy_ovf_template.py.yml
  plugins/modules/vmware_content_deploy_ovf_template.py
Labels: affects_2.10, bug, community_review, gate, has_issue, module, needs_ci, owner_pr, stale_ci

#363 fixed issue where wrong resource pool identifier was returned
  changelogs/fragments/363-vmware_content_deploy_ovf_template.yml
  plugins/module_utils/vmware_rest_client.py
  plugins/modules/vmware_content_deploy_ovf_template.py
Labels: affects_2.10, bug, community_review, gate, module, module_utils, needs_ci, new_contributor, stale_ci
