Repository ansible-collections/community.vmware, pull requests merged in 2020-12, with the labels that each got.

#525 vmware_object_role_permission: allow role names from web UI
  changelogs/fragments/436_vmware_object_role_permission.yml
  plugins/modules/vmware_object_role_permission.py
Labels: feature_request, gate, has_issue

#541 prepare 1.5.1 release
  CHANGELOG.rst
Labels: gate

#543 modify the changelog.yaml for 1.5.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: gate

#542 vmware_object_role_permission: add integration tests
  tests/integration/targets/vmware_object_role_permission/alias
  tests/integration/targets/vmware_object_role_permission/tasks/main.yml
  tests/integration/targets/vmware_object_role_permission/tasks/user_friendly_role_name_tests.yml
  tests/integration/targets/vmware_object_role_permission/tasks/vmware_object_role_permission_tests.yml
Labels: gate

#537 vmware_object_role_permission: add note of separator of domain
  docs/community.vmware.vmware_object_role_permission_module.rst
  plugins/modules/vmware_object_role_permission.py
Labels: docs, gate

#553 Fix CI for default boolean
  plugins/modules/vmware_deploy_ovf.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_file_operation.py
  plugins/modules/vmware_vmkernel.py
  plugins/modules/vmware_vsan_health_info.py
Labels: gate

#511 vmware_guest_network: fix for VMs in a Isolated Private VLAN portgroup
  changelogs/fragments/pvlan_support.yml
  plugins/modules/vmware_guest_network.py
Labels: bug, gate, has_issue

#528 vmware_host_facts: add ESXi host current time info in host facts
  changelogs/fragments/527-vmware_host_facts.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_host_facts.py
  tests/integration/targets/vmware_host_facts/tasks/main.yml
Labels: feature_request, gate, has_issue

#557 vmware_datastore_info: Fix documentation example
  plugins/modules/vmware_datastore_info.py
Labels: gate

#559 vmware_host_logbundle - handle fetch_url status
  changelogs/fragments/vmware_host_logbundle.yml
  plugins/modules/vmware_host_logbundle.py
Labels: bug, gate

#558 vsphere_copy: Handle unboundlocalerror
  changelogs/fragments/554_vsphere_copy.yml
  plugins/modules/vsphere_copy.py
Labels: gate, has_issue

#560 Initial commit for testing document
  README.md
  testing.md
Labels: docs, gate

#552 vmware_guest: Fix an issue with vSphere 7 when adding several HDDs / NICs
  changelogs/fragments/545-vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: bug, gate, has_issue, vSphere7

#566 temporarily disable vmware_migrate_vmk test
  tests/integration/targets/vmware_migrate_vmk/aliases
Labels: gate

#508 vmware_datastore_cluster_manager: new module
  README.md
  docs/community.vmware.vmware_datastore_cluster_manager_module.rst
  meta/runtime.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_datastore_cluster_manager.py
  tests/integration/targets/vmware_datastore_cluster_manager/aliases
  tests/integration/targets/vmware_datastore_cluster_manager/tasks/main.yml
Labels: gate, new_module_request

#577 vmware_dvswitch: Fix idempotency prob with vSphere 7.0.1
  changelogs/fragments/576-vmware_dvswitch.yml
  plugins/modules/vmware_dvswitch.py
Labels: CI, bug, gate, vSphere7

#568 update teardown to support vsphere 7.0u1
  changelogs/fragments/568_teardown_with_esxi.yaml
  tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
Labels: CI, bug, gate

#306 vmware_guest_disk: add SATA and NVMe disk support
  changelogs/fragments/196_vmware_guest_disk.yml
  plugins/modules/vmware_guest_disk.py
  tests/integration/targets/vmware_guest_disk/tasks/main.yml
Labels: affects_2.10, cloud, community_review, feature, gate, integration, module, plugins, tests

#580 vcenter_domain_user_group_info: add a new module
  docs/community.vmware.vcenter_domain_user_group_info_module.rst
  plugins/modules/vcenter_domain_user_group_info.py
  tests/integration/targets/vcenter_domain_user_group_info/aliases
  tests/integration/targets/vcenter_domain_user_group_info/tasks/main.yml
Labels: gate, new_module

#574 vmware_guest: handle computer name while customization
  changelogs/fragments/570_vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: gate, has_issue

#533 vmware_resource_pool: add integration test for using esxi_hostname param
  tests/integration/targets/prepare_vmware_tests/tasks/init_real_lab.yml
  tests/integration/targets/prepare_vmware_tests/tasks/move_host_out_of_cluster.yml
  tests/integration/targets/vmware_resource_pool/aliases
  tests/integration/targets/vmware_resource_pool/tasks/main.yml
Labels: gate

#582 vmware_guest_disk: Fix an issue with vSphere 7 when adding several HDDs
  changelogs/fragments/373-vmware_guest_disk.yml
  plugins/modules/vmware_guest_disk.py
Labels: gate, vSphere7

#491 vmware_guest_file_operation: provide error message
  changelogs/fragments/485_vmware_file_operation.yml
  plugins/modules/vmware_guest_file_operation.py
Labels: gate

#584 vmware_host_iscsi: update EXAMPLE block
  docs/community.vmware.vmware_host_iscsi_module.rst
  plugins/modules/vmware_host_iscsi.py
Labels: docs, gate

#586 vmware_cluster: Consider datacenter while create cluster
  changelogs/fragments/575_vmware_cluster.yml
  plugins/modules/vmware_cluster.py
  plugins/modules/vmware_cluster_drs.py
  plugins/modules/vmware_cluster_ha.py
  plugins/modules/vmware_cluster_vsan.py
Labels: gate, has_issue

#587 vmware_vsan_health_info: Add new parameter 'datacenter'
  changelogs/fragments/vsan_health_info_refactor.yml
  plugins/modules/vmware_vsan_health_info.py
Labels: gate

#588 vmware_host_ntp: Fix issue with disconnected hosts
  changelogs/fragments/539-vmware_host_ntp.yml
  plugins/modules/vmware_host_ntp.py
Labels: bug, gate, has_issue

#589 vmware_host: add a new state option the disconnected
  changelogs/fragments/589_vmware_host.yml
  docs/community.vmware.vmware_host_module.rst
  plugins/modules/vmware_host.py
  tests/integration/targets/vmware_host/tasks/main.yml
Labels: gate
