Repository ansible-collections/community.vmware, pull requests merged in 2021-08, with the labels that each got.

#991 vca: fix validation
  plugins/module_utils/vca.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
Labels: bug, community_review, gate, tests

#977 vmware_portgroup: Improve parameter sanity
  changelogs/fragments/955-vmware_portgroup.yml
  plugins/modules/vmware_portgroup.py
  tests/integration/targets/vmware_portgroup/tasks/main.yml
Labels: gate, has_issue

#983 vmware: Change to use from isinstance to type in if condition
  changelogs/fragments/983-vmware.yml
  plugins/module_utils/vmware.py
  tests/unit/module_utils/test_vmware.py
Labels: bug, community_review, gate, has_issue, module_utils, plugins, tests

#992 vmware: migrate scenario guides from Ansible repo
  README.md
  changelogs/fragments/migrate_vmware_scenario_guides.yml
  docs/community.vmware.vmware_guest_snapshot_info_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_host_kernel_manager_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  docs/docsite/extra-docs.yml
  docs/docsite/rst/scenario_guide.rst
  docs/docsite/rst/vmware_scenarios/faq.rst
  docs/docsite/rst/vmware_scenarios/scenario_clone_template.rst
  docs/docsite/rst/vmware_scenarios/scenario_find_vm_folder.rst
  docs/docsite/rst/vmware_scenarios/scenario_remove_vm.rst
  docs/docsite/rst/vmware_scenarios/scenario_rename_vm.rst
  docs/docsite/rst/vmware_scenarios/scenario_vmware_http.rst
  docs/docsite/rst/vmware_scenarios/scenario_vmware_tools_connection.rst
  docs/docsite/rst/vmware_scenarios/vmware_concepts.rst
  docs/docsite/rst/vmware_scenarios/vmware_external_doc_links.rst
  docs/docsite/rst/vmware_scenarios/vmware_getting_started.rst
  docs/docsite/rst/vmware_scenarios/vmware_intro.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory_filters.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory_hostnames.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory_vm_attributes.rst
  docs/docsite/rst/vmware_scenarios/vmware_module_reference.rst
  docs/docsite/rst/vmware_scenarios/vmware_requirements.rst
  docs/docsite/rst/vmware_scenarios/vmware_scenarios.rst
  docs/docsite/rst/vmware_scenarios/vmware_troubleshooting.rst
  plugins/modules/vmware_host_kernel_manager.py
Labels: gate

#960 Add NVDIMM device support in vmware_guest module
  changelogs/fragments/853-vmware_guest.yml
  plugins/module_utils/vm_device_helper.py
  plugins/module_utils/vmware_spbm.py
  plugins/modules/vmware_guest.py
Labels: gate, feature, has_issue

#933 vmware_guest: Provide a meaningful message when customization failed
  changelogs/fragments/933-vmware_guest_add_msg_customization_failed.yml
  plugins/modules/vmware_guest.py
Labels: gate, feature

#449 vmware_guest_disk: Feature addition RDM Disks
  changelogs/fragments/449-vmware_guest_disk_rdm.yml
  docs/community.vmware.vmware_guest_disk_module.rst
  plugins/modules/vmware_guest_disk.py
Labels: gate, module, community_review, feature, new_contributor, docs, cloud, plugins

#1002 prepare 1.13.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/449-vmware_guest_disk_rdm.yml
  changelogs/fragments/850_vmware_inventory.yml
  changelogs/fragments/853-vmware_guest.yml
  changelogs/fragments/915-vmware_host_datastore.yml
  changelogs/fragments/924-vmware_guest_powerstate.yml
  changelogs/fragments/933-vmware_guest_add_msg_customization_failed.yml
  changelogs/fragments/955-vmware_portgroup.yml
  changelogs/fragments/962-vmware_guest_instant_clone.yml
  changelogs/fragments/976-vmware_host_datastore.yml
  changelogs/fragments/978-vmware_guest_snapshot_info.yml
  changelogs/fragments/983-vmware.yml
  changelogs/fragments/migrate_vmware_scenario_guides.yml
  docs/community.vmware.vmware_guest_module.rst
Labels: gate, needs_triage, community_review, has_issue, docs

#1007 vmware_host_service_manager: Change startup policy without defining state
  changelogs/fragments/916-vmware_host_service_manager.yml
  plugins/modules/vmware_host_service_manager.py
Labels: gate, feature, has_issue

#990 vmware_category: Fix the issue that the error has been occurred when 'All objects' set to associable_object_types
  changelogs/fragments/990-vmware_category.yml
  plugins/modules/vmware_category.py
  tests/integration/targets/vmware_category/tasks/associable_obj_types.yml
Labels: gate
