Repository ansible-collections/community.vmware, pull requests merged in 2021-07, with the labels that each got.

#930 Organize the failed tests as a list in CI
  tests/integration/targets/vmware_host_iscsi/tasks/iscsi_module_test_tasks.yml
  tests/integration/targets/vmware_host_iscsi/tasks/main.yml
  tests/integration/targets/vmware_host_ntp/aliases
  tests/integration/targets/vmware_host_ntp/tasks/main.yml
  tests/integration/targets/vmware_host_tcpip_stacks/aliases
  tests/integration/targets/vmware_object_custom_attributes_info/tasks/main.yml
  tests/integration/targets/vmware_tag_manager/aliases
  tests/integration/targets/vmware_vcenter_settings_info/aliases
Labels: CI, gate, tests, vSphere 7.0.2

#935 prepare 1.12.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
  docs/community.vmware.vmware_content_deploy_template_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
Labels: community_review, docs, gate

#937 readme: clarify we support the last pyvmomi release
  README.md
Labels: gate, needs_info, needs_template, needs_triage, small_patch

#925 Update SDK URL for vmware_guest_info
  plugins/modules/vmware_guest_info.py
Labels: gate

#945 Disable some tests
  tests/integration/targets/inventory_vmware_host_inventory/aliases
  tests/integration/targets/inventory_vmware_vm_inventory/aliases
  tests/integration/targets/vmware_host_service_manager/aliases
Labels: gate, integration

#940 vmware_vcenter_settings_info: Fix the integration test error
  tests/integration/targets/vmware_vcenter_settings_info/aliases
  tests/integration/targets/vmware_vcenter_settings_info/tasks/main.yml
Labels: gate

#949 test: use selinux_please_lie_to_me
  test-requirements.txt
Labels: community_review, gate, needs_triage, small_patch

#950 vmware_portgroup/test: no / in switch name
  tests/integration/targets/vmware_portgroup/tasks/main.yml
Labels: gate

#946 Re-enable inventory tests
  tests/integration/targets/inventory_vmware_host_inventory/aliases
  tests/integration/targets/inventory_vmware_vm_inventory/aliases
Labels: bug, community_review, gate, has_issue, integration, needs_triage, small_patch, tests

#938 vmware_tag_manager: Fix and re-enable integration tests
  tests/integration/targets/vmware_tag_manager/aliases
  tests/integration/targets/vmware_tag_manager/tasks/cleanup.yml
  tests/integration/targets/vmware_tag_manager/tasks/main.yml
  tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
Labels: gate

#924 vmware_guest_powerstate: Fix an error that the datacenter key error has been occurring
  changelogs/fragments/924-vmware_guest_powerstate.yml
  docs/community.vmware.vmware_guest_powerstate_module.rst
  plugins/modules/vmware_guest_powerstate.py
  tests/integration/targets/vmware_guest_powerstate/tasks/main.yml
Labels: gate

#951 vmware_host_ntp: Fix integration test errors
  tests/integration/targets/vmware_host_ntp/aliases
  tests/integration/targets/vmware_host_ntp/tasks/main.yml
Labels: gate

#954 govcsim: wait for govcsim to open up port 8080
  tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim_with_systemd.yml
Labels: bug, community_review, gate, integration, small_patch, tests

#958 tests: disable vmware_guest_instant_clone for now
  tests/integration/targets/vmware_guest_instant_clone/aliases
Labels: gate

#957 tests: remove zuul/vmware/vcenter_1esxi_with_nested
  tests/integration/targets/vmware_first_class_disk/aliases
  tests/integration/targets/vmware_guest/aliases
  tests/integration/targets/vmware_guest_disk_info/aliases
  tests/integration/targets/vmware_guest_instant_clone/aliases
  tests/integration/targets/vmware_guest_network/aliases
  tests/integration/targets/vmware_guest_powerstate/aliases
  tests/integration/targets/vmware_guest_screenshot/aliases
  tests/integration/targets/vmware_guest_tools_wait/aliases
  tests/integration/targets/vmware_vm_inventory/aliases
Labels: gate

#915 vmware_host_datastore: Add a new parameter to expand a datastore capacity
  changelogs/fragments/915-vmware_host_datastore.yml
  docs/community.vmware.vmware_host_datastore_module.rst
  plugins/modules/vmware_host_datastore.py
Labels: feature_request, gate

#967 Revert PR 957
  tests/integration/targets/vmware_first_class_disk/aliases
  tests/integration/targets/vmware_guest/aliases
  tests/integration/targets/vmware_guest_disk_info/aliases
  tests/integration/targets/vmware_guest_instant_clone/aliases
  tests/integration/targets/vmware_guest_network/aliases
  tests/integration/targets/vmware_guest_powerstate/aliases
  tests/integration/targets/vmware_guest_screenshot/aliases
  tests/integration/targets/vmware_guest_tools_wait/aliases
  tests/integration/targets/vmware_vm_inventory/aliases
Labels: CI, gate, tests

#926 Refactor vmware guest controller
  plugins/module_utils/vm_device_helper.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_disk.py
Labels: gate, module_utils, refactor

#961 functional tests run on Ansible 2.11 now
  README.md
Labels: gate, needs_info, needs_template, needs_triage, small_patch

#966 tests: ensure we can create 'VM Network'
  tests/integration/targets/prepare_vmware_tests/tasks/setup_attach_hosts.yml
  tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
  tests/integration/targets/vmware_cluster_info/aliases
Labels: CI, gate

#964 improve code sharing of the inventory plugins
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
  plugins/plugin_utils/inventory.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: bug, cloud, community_review, gate, inventory, new_plugin, plugins, refactor, tests

#968 Improve prepare_vmware_tests
  tests/integration/targets/prepare_vmware_tests/tasks/move_host_out_of_cluster.yml
  tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
  tests/integration/targets/vmware_resource_pool/tasks/main.yml
Labels: bug, gate, integration, needs_triage, tests

#971 Disable vmware_content_library_manager tests
  tests/integration/targets/vmware_content_library_manager/aliases
Labels: gate

#970 Revert "Revert PR 957 (#967)"
  tests/integration/targets/vmware_first_class_disk/aliases
  tests/integration/targets/vmware_guest/aliases
  tests/integration/targets/vmware_guest_disk_info/aliases
  tests/integration/targets/vmware_guest_instant_clone/aliases
  tests/integration/targets/vmware_guest_network/aliases
  tests/integration/targets/vmware_guest_powerstate/aliases
  tests/integration/targets/vmware_guest_screenshot/aliases
  tests/integration/targets/vmware_guest_tools_wait/aliases
  tests/integration/targets/vmware_vm_inventory/aliases
Labels: gate

#972 Fix vmware_vmkernel_ip_config integration tests
  tests/integration/targets/vmware_vmkernel_ip_config/tasks/main.yml
Labels: gate, integration, tests

#962 vmware_guest_instant_clone: Remove the default of the guestinfo_vars and enable the test
  changelogs/fragments/962-vmware_guest_instant_clone.yml
  docs/community.vmware.vmware_guest_instant_clone_module.rst
  plugins/modules/vmware_guest_instant_clone.py
  tests/integration/targets/vmware_guest_instant_clone/aliases
Labels: gate

#974 gitignore: add tests/integration/cloud-config-vcenter.ini
  .gitignore
Labels: community_review, gate, small_patch

#976 vmware_host_datastore: The right error message doesn't be displayed
  changelogs/fragments/976-vmware_host_datastore.yml
  plugins/modules/vmware_host_datastore.py
Labels: gate, module, refactor

#936 vmware_host_tcpip_stacks: Fix and re-enable integration tests
  tests/integration/targets/vmware_host_tcpip_stacks/aliases
  tests/integration/targets/vmware_host_tcpip_stacks/tasks/destroy.yml
  tests/integration/targets/vmware_host_tcpip_stacks/tasks/main.yml
Labels: gate, integration, tests

#978 Add quiesced status in snapshot info
  changelogs/fragments/978-vmware_guest_snapshot_info.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_guest_snapshot_info.py
Labels: feature_request, gate

#893 vmware: filter hosts before templating inventory
  changelogs/fragments/850_vmware_inventory.yml
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
Labels: bug, cloud, community_review, gate, has_issue, inventory, plugins

#985 Delete old changelog fragments
  changelogs/fragments/112-vmware_dvs_host.yml
  changelogs/fragments/738-vmware_content_deploy_xxx.yml
  changelogs/fragments/796-vmware_guest_instant_clone.yml
  changelogs/fragments/816-vmware_guest.yml
  changelogs/fragments/817-vmware_vm_inventory-support-proxy.yml
  changelogs/fragments/819-vmware_vcenter_settings-advanced_setting.yml
  changelogs/fragments/821-vmware_guest_powerstate.yml
  changelogs/fragments/828_vmware_host_vmnic_info.yml
  changelogs/fragments/831-vmware_guest-hostname.yml
  changelogs/fragments/833-vmware_dvswitch-network_policy.yml
  changelogs/fragments/834-vmware_host_tcpip_stacks.yml
  changelogs/fragments/838_vmware_host_custom_attributes.yml
  changelogs/fragments/848_vmware_rest_client_add_support_for_proxy.yml
  changelogs/fragments/851-vmware_object_custom_attributes_info.yml
  changelogs/fragments/855_vmware_host_inventory.yml
  changelogs/fragments/855_vmware_vm_inventory.yml
  changelogs/fragments/858_vmware_vmotion_add_destination_datacenter_parameter.yml
  changelogs/fragments/867-vmware.yml
  changelogs/fragments/872-vmware_host_passthrough.yml
  changelogs/fragments/874-vmware_object_role_permission_info-principal_permissions.yml
  changelogs/fragments/878_vmware_guest_controller.yml
  changelogs/fragments/879-vmware_object_custom_attributes_info.yml
  changelogs/fragments/904-vmware_guest_instant_clone.yml
Labels: community_review, gate, needs_triage, owner_pr
