Repository ansible-collections/community.vmware, pull requests merged in 2021-09, with the labels that each got.

#1019 prepare 1.14.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_host_service_manager_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  tools/prepare_minor_release.yml
Labels: gate, needs_triage, community_review, has_issue, docs

#892 Improve behavior for setting vSAN service on a vmk
  changelogs/fragments/892-vmware_vmkernel.yml
  plugins/modules/vmware_vmkernel.py
Labels: bug, gate, module, community_review, new_contributor, cloud, plugins

#1036 depends on pyvmomi 6.7+
  requirements.txt
  test-requirements.txt
Labels: gate, needs_info, needs_triage, has_issue, needs_template, small_patch

#1023 README: Document docs update and how to prepare a release
  README.md
  tools/create_documentation.yml
  tools/prepare_minor_release.yml
  tools/prepare_release.yml
  tools/update_documentation.yml
Labels: gate, needs_triage, community_review, has_issue, docs

#998 Add a new module vmware_vm_config_option
  changelogs/fragments/993-vmware_vm_config_option.yml
  plugins/module_utils/vm_device_helper.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_vm_config_option.py
  tests/integration/targets/vmware_vm_config_option/aliases
  tests/integration/targets/vmware_vm_config_option/tasks/main.yml
Labels: gate

#1046 Fix sanity / pylint tests
  plugins/modules/vmware_drs_group.py
  plugins/modules/vmware_drs_group_facts.py
  plugins/modules/vmware_drs_group_info.py
  plugins/modules/vmware_host_passthrough.py
  plugins/modules/vmware_vm_host_drs_rule.py
  scripts/inventory/vmware.py
  tests/unit/mock/loader.py
  tests/unit/modules/cloud/vmware/test_vmware_host_sriov.py
Labels: gate, CI, has_issue, tests

#1033 vmware_guest_powerstate: handle 'present' state
  changelogs/fragments/powerstate.yml
  plugins/module_utils/vmware.py
Labels: bug, gate, community_review, module_utils, plugins, small_patch

#1010 vmware_object_rename: add filter parameter to vmware_object_rename
  changelogs/fragments/1010-vmware_object_rename.yml
  docs/community.vmware.vmware_object_rename_module.rst
  plugins/modules/vmware_object_rename.py
Labels: gate

#1040 vmware_guest: Update documentation about "Resources" example
  plugins/modules/vmware_guest.py
Labels: gate, community_review, new_contributor, docs, small_patch

#984 vmware_vm_inventory: Remove erroneous condition
  changelogs/fragments/975_vmware_vm_inventory.yml
  plugins/inventory/vmware_vm_inventory.py
Labels: bug, gate, community_review, has_issue, inventory, cloud, plugins, small_patch

#1020 Fix deploy ovf issue when there are multiple datacenters
  changelogs/fragments/164-vmware_deploy_ovf.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_deploy_ovf.py
Labels: gate

#1024 doc: Add a note about free ESXi license
  docs/docsite/rst/vmware_scenarios/vmware_requirements.rst
  plugins/doc_fragments/vmware.py
  plugins/modules/vmware_target_canonical_facts.py
  plugins/modules/vmware_target_canonical_info.py
Labels: gate, community_review, docs

#1030 vsphere_file: Update `file` example
  plugins/modules/vsphere_file.py
Labels: gate

#1050 vmware_vcenter_settings_info: Fix an issue that Python error has occurred when the schema is vsphere
  changelogs/fragments/1050-vmware_vcenter_settings_info.yml
  plugins/modules/vmware_vcenter_settings_info.py
  tests/integration/targets/vmware_vcenter_settings_info/tasks/main.yml
Labels: bug, gate

#1057 Copy ignore-2.12.txt to ignore-2.13.txt
  changelogs/fragments/0-copy_ignore_txt.yml
  tests/sanity/ignore-2.13.txt
Labels: gate, needs_info, needs_triage, needs_template, tests

#1054 Deprecate vmware_guest_vnc
  changelogs/fragments/deprecate-vmware_guest_vnc.yml
  meta/runtime.yml
  plugins/modules/vmware_guest_vnc.py
  tests/sanity/ignore-2.9.txt
Labels: gate

#870 Add datacenter option to vmware_guest_tools_wait
  changelogs/fragments/870_vmware_guest_tools_wait.yml
  plugins/modules/vmware_guest_tools_wait.py
Labels: bug, gate, module, community_review, has_issue, new_contributor, cloud, plugins
