Repository ansible-collections/community.vmware, pull requests merged in 2021-12, with the labels that each got.

#1013 RDM and Disk Improvements
  changelogs/fragments/1013-vmware_rdm_updates.yml
  plugins/modules/vmware_guest_disk.py
Labels: gate, feature

#1025 vmware_guest: fix the Windows Administrator password being set to string 'None'
  changelogs/fragments/1017-vmware_guest-fix_administrator_password.yml
  plugins/modules/vmware_guest.py
Labels: gate

#1140 prepare 1.17.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1013-vmware_rdm_updates.yml
  changelogs/fragments/1017-vmware_guest-fix_administrator_password.yml
  changelogs/fragments/1044_add_syscontact_syslocation_vmware_host_snmp.yml
  changelogs/fragments/1085_add_show_tag_to_vmware_datastore_info.yml
  changelogs/fragments/1117_add_additional_usb_scan_codes.yml
  changelogs/fragments/rescan_VMFS_feature.yml
  docs/community.vmware.vmware_datastore_info_module.rst
  docs/community.vmware.vmware_guest_disk_module.rst
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_guest_sendkey_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_host_scanhba_module.rst
  docs/community.vmware.vmware_host_snmp_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  docs/community.vmware.vmware_vmotion_module.rst
  docs/community.vmware.vmware_vspan_session_module.rst
  docs/community.vmware.vmware_vswitch_facts_module.rst
  docs/community.vmware.vmware_vswitch_info_module.rst
Labels: gate

#1141 Remove deprecated *_facts modules
  changelogs/fragments/remove_deprecated_facts_modules.yml
  meta/runtime.yml
  plugins/modules/vcenter_extension_facts.py
  plugins/modules/vmware_about_facts.py
  plugins/modules/vmware_category_facts.py
  plugins/modules/vmware_cluster_facts.py
  plugins/modules/vmware_datastore_facts.py
  plugins/modules/vmware_drs_group_facts.py
  plugins/modules/vmware_drs_rule_facts.py
  plugins/modules/vmware_dvs_portgroup_facts.py
  plugins/modules/vmware_guest_boot_facts.py
  plugins/modules/vmware_guest_customization_facts.py
  plugins/modules/vmware_guest_disk_facts.py
  plugins/modules/vmware_guest_facts.py
  plugins/modules/vmware_guest_snapshot_facts.py
  plugins/modules/vmware_host_capability_facts.py
  plugins/modules/vmware_host_config_facts.py
  plugins/modules/vmware_host_dns_facts.py
  plugins/modules/vmware_host_feature_facts.py
  plugins/modules/vmware_host_firewall_facts.py
  plugins/modules/vmware_host_ntp_facts.py
  plugins/modules/vmware_host_package_facts.py
  plugins/modules/vmware_host_service_facts.py
  plugins/modules/vmware_host_ssl_facts.py
  plugins/modules/vmware_host_vmhba_facts.py
  plugins/modules/vmware_host_vmnic_facts.py
  plugins/modules/vmware_local_role_facts.py
  plugins/modules/vmware_local_user_facts.py
  plugins/modules/vmware_portgroup_facts.py
  plugins/modules/vmware_resource_pool_facts.py
  plugins/modules/vmware_tag_facts.py
  plugins/modules/vmware_target_canonical_facts.py
  plugins/modules/vmware_vm_facts.py
  plugins/modules/vmware_vmkernel_facts.py
  plugins/modules/vmware_vswitch_facts.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#1145 vmware_cluster_drs/ha/vsan remove alias and change default for enable
  changelogs/fragments/vmware_cluster_drs-ha-vsan-enable_default.yml
  plugins/modules/vmware_cluster_drs.py
  plugins/modules/vmware_cluster_ha.py
  plugins/modules/vmware_cluster_vsan.py
  tests/integration/targets/vmware_cluster_drs/tasks/main.yml
  tests/integration/targets/vmware_cluster_ha/tasks/main.yml
  tests/integration/targets/vmware_cluster_vsan/tasks/main.yml
Labels: gate

#1156 Fix version_added of vmware_guest.advanced_settings
  plugins/modules/vmware_guest.py
Labels: gate

#1157 [backport] vmware_guest: Fix version_added of advanced_settings
  plugins/modules/vmware_guest.py
Labels: documentation, gate

#1144 Remove deprecated vmware_vmkernel_ip_config module
  changelogs/fragments/remove_vmware_vmkernel_ip_config.yml
  meta/runtime.yml
  plugins/modules/vmware_vmkernel_ip_config.py
  tests/integration/targets/vmware_vmkernel_ip_config/aliases
  tests/integration/targets/vmware_vmkernel_ip_config/tasks/main.yml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#1153 Prune references to old facts from new info modules
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_datastore_info.py
  plugins/modules/vmware_guest_info.py
  plugins/modules/vmware_guest_snapshot_info.py
  plugins/modules/vmware_tag_info.py
  plugins/modules/vmware_vm_info.py
Labels: gate

#1113 fix folders collision
  changelogs/fragments/1112-vcenter_folder.yml
  plugins/modules/vcenter_folder.py
  tests/integration/targets/vcenter_folder/tasks/main.yml
  tests/integration/targets/vcenter_folder/tasks/regression_folder_collision.yml
Labels: gate

#1148 vmware_cluster: Remove deprecated features
  changelogs/fragments/vmware_cluster-remove-deprecated-features.yml
  plugins/modules/vmware_cluster.py
Labels: gate

#1150 vmware_dvs_portgroup: Remove portgroup_type
  changelogs/fragments/vmware_dvs_portgroup-portgroup_type.yml
  plugins/modules/vmware_dvs_portgroup.py
  tests/integration/targets/prepare_vmware_tests/tasks/setup_dvs_portgroup.yml
  tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
  tests/integration/targets/vmware_dvs_portgroup_find/tasks/main.yml
  tests/integration/targets/vmware_dvs_portgroup_info/tasks/main.yml
  tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
  tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
  tests/integration/targets/vmware_guest_network/tasks/main.yml
  tests/integration/targets/vmware_migrate_vmk/tasks/main.yml
  tests/integration/targets/vmware_vspan_session/tasks/main.yml
Labels: gate

#1149 vmware_guest: Make VBS requirements explicit
  changelogs/fragments/vmware_guest-vbs.yml
  plugins/modules/vmware_guest.py
Labels: gate

#1161 vmware_export_ovf: add export with extra config support
  changelogs/fragments/vmware_export_ovf.yml
  plugins/modules/vmware_export_ovf.py
Labels: gate

#1165 Prepare for distutils.version being removed in Python 3.12
  changelogs/fragments/disutils.version.yml
  plugins/module_utils/version.py
  plugins/modules/vmware_category.py
  plugins/modules/vmware_vc_infraprofile_info.py
Labels: gate
