Repository ansible-collections/community.vmware, pull requests merged in 2021-10, with the labels that each got.

#1063 ignore-2.13: drop the py2.6 compile entries
  tests/sanity/ignore-2.13.txt
Labels: gate, needs_info, needs_template, tests

#1060 Improve tools/ naming
  tools/create_documentation_tasks.yml
  tools/prepare_release.yml
  tools/update_documentation.yml
Labels: gate, needs_info, needs_triage, needs_template

#1065 vmware_deploy_ovf: Fix to display suitable the error
  changelogs/fragments/1065-vmware_deploy_ovf.yml
  plugins/modules/vmware_deploy_ovf.py
Labels: gate
