Repository ansible-collections/community.vmware, pull requests merged in 2021-11, with the labels that each got.

#1055 vmware_guest_serial_port: Handle serial backing type
  changelogs/fragments/1043_vmware_guest_serial.yml
  plugins/modules/vmware_guest_serial_port.py
Labels: bug, gate

#1096 vmware_vswitch: Add example to delete a vswitch on a ESXi host
  docs/community.vmware.vmware_vswitch_module.rst
  plugins/modules/vmware_vswitch.py
Labels: documentation, gate

#1097 vca_fw: Removed state set to absent from the example
  docs/community.vmware.vca_fw_module.rst
  plugins/modules/vca_fw.py
Labels: gate

#1095 prepare 1.16.0 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1043_vmware_guest_serial.yml
  changelogs/fragments/1082_vmware.yml
  changelogs/fragments/1083_vmware_host_lockdown.yml
  changelogs/fragments/840_vmware_vswitch.yml
  changelogs/fragments/996_vmware_guest_cross_vc_clone.yml
  docs/community.vmware.vmware_guest_cross_vc_clone_module.rst
  docs/community.vmware.vmware_guest_tpm_module.rst
Labels: gate, needs_triage, community_review, docs

#1085 Added Tagging to vmware_datastore_info
  changelogs/fragments/1085_add_show_tag_to_vmware_datastore_info.yml
  plugins/module_utils/vmware_rest_client.py
  plugins/modules/vmware_datastore_info.py
  tests/integration/targets/vmware_datastore_info/tasks/main.yml
Labels: gate

#1102 vmware_dvs_portgroup_find/test: ignore the result order
  tests/integration/targets/vmware_dvs_portgroup_find/tasks/main.yml
Labels: gate

#1091 Document checking out a PR
  testing.md
Labels: documentation, gate, community_review, docs

#1116 vmware_guest_disk/test: use vmx-13
  tests/integration/targets/vmware_guest_disk/tasks/main.yml
Labels: gate

#1123 vmware_guest/tests: drop useless tests
  tests/integration/targets/vmware_guest/defaults/main.yml
  tests/integration/targets/vmware_guest/tasks/poweroff_d1_c1_f0.yml
  tests/integration/targets/vmware_guest/tasks/poweroff_d1_c1_f1.yml
Labels: gate

#1121 disable vmware_host_tcpip_stacks/tests for now
  tests/integration/targets/vmware_host_tcpip_stacks/aliases
Labels: gate

#1128 vmware_vcenter_settings/tests: restore advanced_settings config
  tests/integration/targets/vmware_vcenter_settings/tasks/main.yml
Labels: gate

#1115 temporarily disable vmware_migrate_vmk
  tests/integration/targets/vmware_migrate_vmk/aliases
Labels: gate

#1117 vmware_guest_sendkey: add additional USB scan codes for `HOME` and `END`
  changelogs/fragments/1117_add_additional_usb_scan_codes.yml
  plugins/modules/vmware_guest_sendkey.py
Labels: gate, feature

#1126 vmware_vm_host_drs_rule/tests: clean up resources
  tests/integration/targets/vmware_vm_host_drs_rule/tasks/main.yml
Labels: gate, CI

#1127 vmware_datastore_cluster/test: clean up resources
  tests/integration/targets/vmware_datastore_cluster/tasks/main.yml
Labels: gate, CI

#1130 vmware_vm_inventory/tests: only spawn 1 VM with 1GB of RAM
  tests/integration/targets/vmware_vm_inventory/prepare_environment.yml
  tests/integration/targets/vmware_vm_inventory/test_inventory.yml
Labels: gate

#1105 always use debian8_64Guest in our functinal tests
  tests/integration/targets/vmware_guest/tasks/clone_resize_disks.yml
  tests/integration/targets/vmware_guest/tasks/create_vm_using_special_characters.yml
  tests/integration/targets/vmware_guest/tasks/network_with_device.yml
  tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
  tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
  tests/integration/targets/vmware_guest/tasks/reconfig_vm_to_latest_version.yml
  tests/integration/targets/vmware_guest_network/tasks/main.yml
  tests/integration/targets/vmware_guest_tools_wait/tasks/main.yml
  tests/integration/targets/vmware_host_auto_start/tasks/main.yml
  tests/integration/targets/vmware_vmotion/tasks/main.yml
Labels: gate

#1131 vmware_vmkernel_ip_config/tests: avoid IPv4 conflict
  tests/integration/targets/vmware_vmkernel_ip_config/tasks/main.yml
Labels: gate

#1110 vmware_guest/test: reduce network_with_device res usage
  tests/integration/targets/vmware_guest/tasks/network_with_device.yml
Labels: gate

#1107 tests: use hw version 11
  tests/integration/targets/prepare_vmware_tests/tasks/setup_virtualmachines.yml
  tests/integration/targets/vmware_guest/tasks/create_rp_d1_c1_f0.yml
  tests/integration/targets/vmware_guest/tasks/network_with_device.yml
  tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
  tests/integration/targets/vmware_guest_network/tasks/main.yml
  tests/integration/targets/vmware_guest_tools_wait/tasks/main.yml
  tests/integration/targets/vmware_host_auto_start/tasks/main.yml
  tests/integration/targets/vmware_vmotion/tasks/main.yml
Labels: gate

#1132 vmware_content_library_manager: reenable the tests
  tests/integration/targets/vmware_content_library_manager/aliases
  tests/integration/targets/vmware_content_library_manager/tasks/main.yml
Labels: gate

#1125 tests: use vmware.vmware_rest to clean up the resources
  test-requirements.txt
  tests/integration/targets/prepare_vmware_tests/tasks/setup_virtualmachines.yml
  tests/integration/targets/prepare_vmware_tests/tasks/teardown.yml
  tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
  tests/integration/targets/vmware_guest/tasks/check_mode.yml
  tests/integration/targets/vmware_guest/tasks/clone_customize_guest_test.yml
  tests/integration/targets/vmware_guest/tasks/clone_with_convert.yml
  tests/integration/targets/vmware_guest/tasks/main.yml
  tests/integration/targets/vmware_guest/tasks/run_test_playbook.yml
  tests/integration/targets/vmware_guest_disk_info/tasks/main.yml
  tests/integration/targets/vmware_host_datastore/tasks/main.yml
  tests/integration/targets/vmware_host_firewall_manager/tasks/main.yml
Labels: gate

#1108 tests: remove linked_clone_d1_c1_f0.yml
  tests/integration/targets/vmware_guest/defaults/main.yml
  tests/integration/targets/vmware_guest/tasks/linked_clone_d1_c1_f0.yml
Labels: gate

#1103 vmware_host_snmp: Add code to support SNMP values
  changelogs/fragments/1044_add_syscontact_syslocation_vmware_host_snmp.yml
  plugins/modules/vmware_host_snmp.py
  tests/integration/targets/vmware_host_snmp/tasks/main.yml
Labels: gate

#1100 Replace firewall with vswitch in vswitch info and facts files
  plugins/modules/vmware_vswitch_facts.py
  plugins/modules/vmware_vswitch_info.py
Labels: gate, docs

#1135 Update example task names in vmotion and vspan modules
  plugins/modules/vmware_vmotion.py
  plugins/modules/vmware_vspan_session.py
Labels: gate

#1137 vmware_host_scanhba: rescan VMFS feature
  changelogs/fragments/rescan_VMFS_feature.yml
  plugins/modules/vmware_host_scanhba.py
Labels: gate
