Repository ansible-collections/community.vmware, pull requests merged in 2022-12, with the labels that each got.

#1562 Fixes 20221201
  meta/runtime.yml
  plugins/modules/vmware_custom_attribute.py
  plugins/modules/vmware_custom_attribute_manager.py
Labels: mergeit

#1563 2.x: Fix meta/runtime.yml
  meta/runtime.yml
Labels: bug, community_review, mergeit

#1565 prepare 2.10.2 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1477-vmware_object_custom_attributes_info.yml
  changelogs/fragments/1522-vmware_dvs_portgroup.yml
  changelogs/fragments/1544-vmware_portgroup_info.yml
  changelogs/fragments/1555-vmware_guest_instant_clone-pyvmomi_8_0_0_1.yml
  docs/community.vmware.vcenter_standard_key_provider_module.rst
  docs/community.vmware.vmware_content_library_manager_module.rst
  docs/community.vmware.vmware_dvs_host_module.rst
  docs/community.vmware.vmware_dvswitch_lacp_module.rst
  docs/community.vmware.vmware_dvswitch_nioc_module.rst
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_guest_network_module.rst
  docs/community.vmware.vmware_guest_sendkey_module.rst
  docs/community.vmware.vmware_host_active_directory_module.rst
  docs/community.vmware.vmware_host_snmp_module.rst
  galaxy.yml
Labels: community_review, docs, mergeit

#1566 Remove version 3.2.0 from galaxy.yml
  galaxy.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1567 Remove version 2.10.2 from galaxy.yml
  galaxy.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1542 vmware_cluster_drs - Add predictive DRS Setting
  changelogs/fragments/1542-vmware_cluster_drs.yaml
  plugins/modules/vmware_cluster_drs.py
  tests/integration/targets/vmware_cluster_drs/tasks/main.yml
Labels: bug, feature, mergeit

#1553 vmware_guest: Fix check mode
  changelogs/fragments/1272-vmware_guest-check_mode.yml
  plugins/modules/vmware_guest.py
  tests/integration/targets/vmware_guest/tasks/advanced_settings.yml
  tests/integration/targets/vmware_guest/tasks/cdrom_d1_c1_f0.yml
  tests/integration/targets/vmware_guest/tasks/cdrom_d1_c1_f1.yml
  tests/integration/targets/vmware_guest/tasks/check_mode.yml
  tests/integration/targets/vmware_guest/tasks/reconfig_vm_to_latest_version.yml
  tests/integration/targets/vmware_guest/tasks/windows_vbs_d1_c1_f0.yml
Labels: bug, has_issue, mergeit
