Repository ansible-collections/community.vmware, pull requests merged in 2022-09, with the labels that each got.

#1441 fix replace http with https for port 443 on cfg restore
  changelogs/fragments/1440-vmware_cfg_backup-fails-to-restore-port-80-blocked.yaml
  plugins/modules/vmware_cfg_backup.py
Labels: mergeit

#1445 vmware_guest_boot_manager: Add initial integration test
  tests/integration/targets/vmware_guest_boot_manager/aliases
  tests/integration/targets/vmware_guest_boot_manager/tasks/main.yml
Labels: integration, tests, mergeit

#1448 vmware_drs_group_manager: Improve error handling
  changelogs/fragments/1448-vmware_drs_group_manager-error_msg.yml
  plugins/modules/vmware_drs_group_manager.py
Labels: mergeit

#1437 vmware_content_library_info: Add Subscribed Libraries
  changelogs/fragments/1430-vmware_content_library_info-add_subscribed_libraries.yaml
  plugins/modules/vmware_content_library_info.py
Labels: feature, has_issue, mergeit

#1450 prepare 2.9.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  galaxy.yml
Labels: community_review, mergeit

#1451 Remove version 2.9.1 from galaxy.yml
  galaxy.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1453 Remove deprecated vca modules
  changelogs/fragments/remove_deprecated_vca_modules.yml
  meta/runtime.yml
  plugins/doc_fragments/vca.py
  plugins/module_utils/vca.py
  plugins/modules/vca_fw.py
  plugins/modules/vca_nat.py
  plugins/modules/vca_vapp.py
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
Labels: mergeit

#1454 vmware_guest_vnc: Remove deprecated module
  changelogs/fragments/remove_deprecated_vmware_guest_vnc_module.yml
  meta/runtime.yml
  plugins/modules/vmware_guest_vnc.py
Labels: mergeit

#1455 vmware_dns_config: Remove deprecated module
  changelogs/fragments/remove_deprecated_dns_config_module.yml
  meta/runtime.yml
  plugins/modules/vmware_dns_config.py
Labels: mergeit

#1456 vsphere_copy: Remove deprecated parameters
  changelogs/fragments/1196-vsphere_copy-remove_deprecated_parameters.yml
  plugins/modules/vsphere_copy.py
Labels: mergeit

#1457 vmware_vm_config_option: Change item names in result
  changelogs/fragments/1268-vmware_vm_config_option-change_result.yml
  plugins/modules/vmware_vm_config_option.py
  tests/integration/targets/vmware_vm_config_option/tasks/main.yml
Labels: mergeit

#1461 vmware_guest_boot_manager: Remove secure_boot_enabled default
  changelogs/fragments/1257-vmware_guest_boot_manager-remove_secure_boot_default.yml
  plugins/modules/vmware_guest_boot_manager.py
  tests/integration/targets/vmware_guest_boot_manager/tasks/main.yml
Labels: mergeit

#1459 vmware_guest_network: Remove deprecated parameter networks
  changelogs/fragments/1195-vmware_guest_network-remove_networks.yml
  plugins/modules/vmware_guest_network.py
  tests/integration/targets/vmware_guest_network/tasks/main.yml
Labels: mergeit

#1463 vmware_host_firewall_manager: Remove deprecated functionality
  changelogs/fragments/1196-vmware_host_firewall_manager-remove_deprecated_stuff.yml
  plugins/modules/vmware_host_firewall_manager.py
  tests/integration/targets/vmware_host_firewall_manager/tasks/main.yml
Labels: mergeit

#1467 Fix sanity for 2.15 tests
  tests/sanity/ignore-2.15.txt
Labels: community_review, tests, mergeit

#1468 Fix sanity for 2.15 tests (#1467)
  tests/sanity/ignore-2.15.txt
Labels: community_review, tests, mergeit

#1465 vmware_tag_manager: Fix idempotency for state set
  changelogs/fragments/1265-vmware_tag_manager-set_idempotency.yml
  plugins/modules/vmware_tag_manager.py
  tests/integration/targets/vmware_tag_manager/tasks/cleanup.yml
  tests/integration/targets/vmware_tag_manager/tasks/main.yml
  tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
Labels: bug, mergeit

#1469 vmware_tag_manager: Fix idempotency for state set
  changelogs/fragments/1265-vmware_tag_manager-set_idempotency.yml
  plugins/modules/vmware_tag_manager.py
  tests/integration/targets/vmware_tag_manager/tasks/cleanup.yml
  tests/integration/targets/vmware_tag_manager/tasks/main.yml
  tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
Labels: bug, mergeit

#1470 vmware_dvs_portgroup - Update Netflow Settings of DVS not Work (#1443)
  changelogs/fragments/1443-vmware_dvs_portgroup-update_netflow_not_work.yaml
  plugins/modules/vmware_dvs_portgroup.py
Labels: bug, mergeit

#1473 Remove version_added: 1.x part 1
  plugins/modules/vcenter_domain_user_group_info.py
  plugins/modules/vmware_cluster_ha.py
  plugins/modules/vmware_content_deploy_ovf_template.py
  plugins/modules/vmware_content_deploy_template.py
  plugins/modules/vmware_content_library_manager.py
  plugins/modules/vmware_datastore_info.py
  plugins/modules/vmware_deploy_ovf.py
  plugins/modules/vmware_drs_group_manager.py
  plugins/modules/vmware_dvs_host.py
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_dvs_portgroup_info.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_first_class_disk.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_cross_vc_clone.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_info.py
  plugins/modules/vmware_guest_instant_clone.py
  plugins/modules/vmware_guest_network.py
  plugins/modules/vmware_guest_powerstate.py
  plugins/modules/vmware_guest_sendkey.py
Labels: documentation, mergeit

#1474 Remove version_added: 1.x part 2
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_cluster_vsan.py
  plugins/modules/vmware_guest_storage_policy.py
  plugins/modules/vmware_guest_tools_wait.py
  plugins/modules/vmware_guest_tpm.py
  plugins/modules/vmware_host_custom_attributes.py
  plugins/modules/vmware_host_datastore.py
  plugins/modules/vmware_host_iscsi.py
  plugins/modules/vmware_host_passthrough.py
  plugins/modules/vmware_host_scanhba.py
  plugins/modules/vmware_host_snmp.py
  plugins/modules/vmware_host_sriov.py
  plugins/modules/vmware_host_tcpip_stacks.py
  plugins/modules/vmware_object_custom_attributes_info.py
  plugins/modules/vmware_object_role_permission_info.py
  plugins/modules/vmware_recommended_datastore.py
  plugins/modules/vmware_resource_pool.py
  plugins/modules/vmware_tag_manager.py
  plugins/modules/vmware_vc_infraprofile_info.py
  plugins/modules/vmware_vcenter_settings.py
  plugins/modules/vmware_vm_config_option.py
  plugins/modules/vmware_vm_storage_policy.py
  plugins/modules/vmware_vmotion.py
  plugins/modules/vmware_vsan_health_info.py
Labels: documentation, mergeit

#1475 New module vmware_datastore
  plugins/modules/vmware_datastore.py
  tests/integration/targets/vmware_datastore/aliases
  tests/integration/targets/vmware_datastore/tasks/main.yml
Labels: new_module, mergeit

#1466 vmware_guest_disk: Add iolimit modifications on an existing disk with…
  changelogs/fragments/1466-vmware_guest_disk-change_iolimit_without_size.yml
  plugins/modules/vmware_guest_disk.py
Labels: feature, mergeit

#1478 vmware_guest_disk: Backport #1466
  changelogs/fragments/1466-vmware_guest_disk-change_iolimit_without_size.yml
  plugins/modules/vmware_guest_disk.py
Labels: feature, mergeit

#1476 [WIP] securityPolicy: Deprecated as of vSphere API 6.7
  changelogs/fragments/vmware_dvs_portgroup-securityPolicy.yml
  changelogs/fragments/vmware_dvs_portgroup_info-securityPolicy.yml
  changelogs/fragments/vmware_dvswitch-securityPolicy.yml
  changelogs/fragments/vmware_dvswitch_uplink_pg-securityPolicyOverrideAllowed.yml
  changelogs/fragments/vmware_vspan_session-securityPolicy.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_dvs_portgroup_info.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_dvswitch_uplink_pg.py
  plugins/modules/vmware_vspan_session.py
Labels: mergeit

#1481 Fix required ansible-core version
  changelogs/fragments/1481-required_ansible_version.yml
  meta/runtime.yml
Labels: bug, community_review, small_patch, mergeit

#1482 3.0.0: Removing support for ansible-core version < 2.13.0
  changelogs/fragments/3.0.0-required_ansible_version.yml
  meta/runtime.yml
  tests/sanity/ignore-2.12.txt
Labels: community_review, tests, docs, mergeit
