Repository ansible-collections/community.vmware, pull requests merged in 2022-06, with the labels that each got.

#1337 vmware_host_vmnic_info: Fix issue with offline / disconnected / shut down hosts
  changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
  plugins/modules/vmware_host_vmnic_info.py
  tests/integration/targets/vmware_host_vmnic_info/tasks/main.yml
Labels: bug, integration, owner_pr, mergeit

#1335 fix replace http with https when using port 443
  changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
  plugins/modules/vmware_cfg_backup.py
Labels: bug, has_issue, mergeit

#1339 PR 1329: Bugfix instead of minor change
  changelogs/fragments/184_vmware_host_facts.yml
Labels: bug, community_review, owner_pr, mergeit

#1340 prepare 2.6.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1240-vmware_vmotion-add_cluster_storage_cluster.yaml
  changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
  changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
  changelogs/fragments/184_vmware_host_facts.yml
  docs/community.vmware.vmware_host_facts_module.rst
  docs/community.vmware.vmware_vmotion_module.rst
  galaxy.yml
Labels: community_review, docs, mergeit

#1341 Remove version 2.6.0 from galaxy.yml
  galaxy.yml
Labels: community_review, docs, small_patch, mergeit

#1343 Backport PR #1329 to stable-1
  changelogs/fragments/184_vmware_host_facts.yml
  plugins/modules/vmware_host_facts.py
  tests/integration/targets/vmware_host_facts/aliases
  tests/integration/targets/vmware_host_facts/tasks/main.yml
Labels: bug, mergeit

#1345 Backport PR #1337 to stable-1
  changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
  plugins/modules/vmware_host_vmnic_info.py
  tests/integration/targets/vmware_host_vmnic_info/tasks/main.yml
Labels: bug, mergeit

#1346 Backport PR #1335 to stable-1
  changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
  plugins/modules/vmware_cfg_backup.py
Labels: bug, mergeit

#1348 prepare 1.18.1 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
  changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
  changelogs/fragments/184_vmware_host_facts.yml
  docs/community.vmware.vmware_host_facts_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
Labels: bug, community_review, docs, mergeit

#1338 vmware_object_role_permission and info - Add StoragePod to the List of object types
  changelogs/fragments/1338-vmware_object_role_permission-and-vmware_object_role_permission_info.yaml
  plugins/modules/vmware_object_role_permission.py
  plugins/modules/vmware_object_role_permission_info.py
Labels: feature, mergeit

#1350 Set version 2 EOL to Nov 2023
  README.md
Labels: community_review, docs, small_patch, mergeit

#1351 vmware_dvswitch_nioc - Add backupNfc and nvmetcp to the resources
  changelogs/fragments/1351-vmaware_dvswitch_nioc.yaml
  plugins/modules/vmware_dvswitch_nioc.py
Labels: mergeit

#1321 vmware_guest_disk: Avoid using in maintenance DS
  changelogs/fragments/1321-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
  plugins/modules/vmware_guest_disk.py
Labels: mergeit

#1357 Backport vmware_guest_disk: Avoid using in maintenance DS
  changelogs/fragments/1321-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
  plugins/modules/vmware_guest_disk.py
Labels: bug, mergeit

#1362 ISSUE-1290 Remove cluster host fm Pools
  plugins/modules/vmware_content_deploy_ovf_template.py
  plugins/modules/vmware_content_deploy_template.py
Labels: bug, has_issue, mergeit

#1366 Changelog fragment for PR #1362
  changelogs/fragments/1362.yml
Labels: community_review, owner_pr, docs, mergeit

#1367 Backport PR #1362 to stable-1
  changelogs/fragments/1362.yml
  plugins/modules/vmware_content_deploy_ovf_template.py
  plugins/modules/vmware_content_deploy_template.py
Labels: bug, mergeit

#1368 prepare 1.18.2 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1321-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
  changelogs/fragments/1362.yml
Labels: bug, community_review, mergeit

#1317 fixed typo related to guest MTU
  plugins/modules/vmware_guest_network.py
Labels: bug, mergeit

#1371 Update link to dev guide
  README.md
Labels: community_review, docs, small_patch, mergeit

#1318 fix type issue with VirtualPCIPassthrough
  plugins/modules/vmware_guest_network.py
Labels: mergeit

#1374 Changelog fragment for PR #1318
  changelogs/fragments/1318-vmware_guest_network-attribute_error.yml
Labels: community_review, owner_pr, docs, mergeit
