Repository ansible-collections/community.vmware, pull requests merged in 2022-02, with the labels that each got.

#1213 Fix changelog fragments
  changelogs/fragments/datastore_url-added-to-vm_info.yaml
Labels: community_review, owner_pr, docs, mergeit

#1210 Added support for multiple SCSI controllers
  changelogs/fragments/1203-vmware_guest_storage_policy-controller_number-param.yml
  docs/community.vmware.vmware_guest_storage_policy_module.rst
  plugins/modules/vmware_guest_storage_policy.py
  tests/integration/targets/vmware_guest_storage_policy/tasks/main.yml
Labels: mergeit

#1226 don't test inventory_vmware_vm_inventory with govcsim
  tests/integration/targets/inventory_vmware_vm_inventory/aliases
Labels: community_review, integration, tests, small_patch, mergeit

#1215 Remove pre-collection version_added documentation
  changelogs/fragments/remove_pre-collection_version_added.yml
  plugins/doc_fragments/vmware.py
  plugins/inventory/vmware_vm_inventory.py
Labels: community_review, has_issue, inventory, docs, cloud, plugins, small_patch, mergeit

#1167 Add new module vcenter_standard_key_provider
  plugins/module_utils/vmware.py
  plugins/modules/vcenter_standard_key_provider.py
Labels: mergeit

#1176 added DistributedVirtualPortgroup object_type
  changelogs/fragments/1176-vmware_dv_portgroup.yml
  plugins/modules/vmware_object_role_permission.py
Labels: mergeit

#1228 Remove FQCN from jsonfile plugin in tests
  tests/integration/targets/inventory_vmware_host_inventory/runme.sh
  tests/integration/targets/inventory_vmware_vm_inventory/aliases
  tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
  tests/integration/targets/vmware_vm_inventory/ansible.cfg
Labels: bug, needs_triage, CI, community_review, has_issue, integration, tests, mergeit

#1211 Fix getting the next release
  tools/prepare_release.yml
Labels: bug, community_review, small_patch, mergeit
