Repository ansible-collections/community.vmware, pull requests merged in 2022-08, with the labels that each got.

#1421 Fix new lint errors
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_guest_register_operation.py
  plugins/modules/vmware_vspan_session.py
Labels: CI, mergeit

#1422 vmware_host_logbundle: retry on download error
  tests/integration/targets/vmware_host_logbundle/tasks/main.yml
Labels: CI, tests, mergeit

#1418 vmware_host_vmnic_info: added CDP information
  changelogs/fragments/1418_vmware_host_vmnic_info.yml
  plugins/modules/vmware_host_vmnic_info.py
Labels: feature, mergeit

#1426 prepare 2.8.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1376-vmware_guest_sendkey-add-ctrl_x-support.yaml
  changelogs/fragments/1388-vmware_cfg_backup-improve_error_msg.yml
  changelogs/fragments/1392-proposed_fixes_for_backup_behavior_1383.yml
  changelogs/fragments/1402-vmware_guest_change_to_fail_json.yml
  changelogs/fragments/1407-vmware_vm_info-inaccessible_vm.yml
  changelogs/fragments/1418_vmware_host_vmnic_info.yml
  changelogs/fragments/1419-vmware_dvs_portgroup-problem_with_spec_numPorts_is_none_solved.yaml
  galaxy.yml
Labels: mergeit

#1427 Remove version 2.8.0 from galaxy.yml
  galaxy.yml
Labels: small_patch, mergeit

#1429 Fix pylint issues
  plugins/connection/vmware_tools.py
  plugins/modules/vmware_cluster_vsan.py
  plugins/modules/vmware_local_user_info.py
  plugins/modules/vmware_vsan_health_info.py
  scripts/inventory/vmware.py
  scripts/inventory/vmware_inventory.py
Labels: bug, connection, cloud, plugins, small_patch, mergeit

#1436 vmware_vswitch: Fix the broken logic of the failback parameter
  changelogs/fragments/1431-vmware_vswitch-fix_failback.yml
  plugins/modules/vmware_vswitch.py
Labels: bug, has_issue, mergeit
