Repository ansible-collections/community.vmware, pull requests merged in 2022-10, with the labels that each got.

#1483 vmware_dvs_portgroup : Remove defaults and add explicit inheritance from switch defaults
  changelogs/fragments/1483-vmware_dvs_portgroup.yml
  plugins/modules/vmware_dvs_portgroup.py
  tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
  tests/integration/targets/vmware_vspan_session/tasks/main.yml
Labels: feature, mergeit

#1488 Add 3.0.0 to README
  README.md
Labels: community_review, docs, small_patch, mergeit

#1489 Add 3.0.0 to README (backport #1488)
  README.md
Labels: community_review, docs, small_patch, mergeit

#1490 Update changelog fragments for a better porting guide
  changelogs/fragments/1195-vmware_guest_network-remove_networks.yml
  changelogs/fragments/1196-vmware_host_firewall_manager-remove_deprecated_stuff.yml
  changelogs/fragments/1196-vsphere_copy-remove_deprecated_parameters.yml
  changelogs/fragments/1257-vmware_guest_boot_manager-remove_secure_boot_default.yml
  changelogs/fragments/1483-vmware_dvs_portgroup.yml
  changelogs/fragments/remove_deprecated_dns_config_module.yml
  changelogs/fragments/remove_deprecated_vmware_guest_vnc_module.yml
Labels: community_review, owner_pr, docs, mergeit

#1493 Update docs for 3.0.0
  docs/community.vmware.vcenter_domain_user_group_info_module.rst
  docs/community.vmware.vmware_cluster_ha_module.rst
  docs/community.vmware.vmware_cluster_info_module.rst
  docs/community.vmware.vmware_cluster_vsan_module.rst
  docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
  docs/community.vmware.vmware_content_deploy_template_module.rst
  docs/community.vmware.vmware_content_library_manager_module.rst
  docs/community.vmware.vmware_datastore_info_module.rst
  docs/community.vmware.vmware_deploy_ovf_module.rst
  docs/community.vmware.vmware_drs_group_manager_module.rst
  docs/community.vmware.vmware_dvs_host_module.rst
  docs/community.vmware.vmware_dvs_portgroup_info_module.rst
  docs/community.vmware.vmware_dvs_portgroup_module.rst
  docs/community.vmware.vmware_dvswitch_module.rst
  docs/community.vmware.vmware_first_class_disk_module.rst
  docs/community.vmware.vmware_guest_boot_manager_module.rst
  docs/community.vmware.vmware_guest_controller_module.rst
  docs/community.vmware.vmware_guest_cross_vc_clone_module.rst
  docs/community.vmware.vmware_guest_disk_module.rst
  docs/community.vmware.vmware_guest_info_module.rst
  docs/community.vmware.vmware_guest_instant_clone_module.rst
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_guest_network_module.rst
  docs/community.vmware.vmware_guest_powerstate_module.rst
  docs/community.vmware.vmware_guest_sendkey_module.rst
  docs/community.vmware.vmware_guest_storage_policy_module.rst
  docs/community.vmware.vmware_guest_tools_wait_module.rst
  docs/community.vmware.vmware_guest_tpm_module.rst
  docs/community.vmware.vmware_host_custom_attributes_module.rst
  docs/community.vmware.vmware_host_datastore_module.rst
  docs/community.vmware.vmware_host_firewall_manager_module.rst
  docs/community.vmware.vmware_host_iscsi_module.rst
  docs/community.vmware.vmware_host_passthrough_module.rst
  docs/community.vmware.vmware_host_scanhba_module.rst
  docs/community.vmware.vmware_host_snmp_module.rst
  docs/community.vmware.vmware_host_sriov_module.rst
  docs/community.vmware.vmware_host_tcpip_stacks_module.rst
  docs/community.vmware.vmware_object_custom_attributes_info_module.rst
  docs/community.vmware.vmware_object_role_permission_info_module.rst
  docs/community.vmware.vmware_recommended_datastore_module.rst
  docs/community.vmware.vmware_resource_pool_module.rst
  docs/community.vmware.vmware_tag_manager_module.rst
  docs/community.vmware.vmware_vc_infraprofile_info_module.rst
  docs/community.vmware.vmware_vcenter_settings_module.rst
  docs/community.vmware.vmware_vm_config_option_module.rst
  docs/community.vmware.vmware_vm_storage_policy_module.rst
  docs/community.vmware.vmware_vmotion_module.rst
  docs/community.vmware.vmware_vsan_health_info_module.rst
  docs/community.vmware.vsphere_copy_module.rst
Labels: community_review, docs, mergeit

#1494 prepare 3.0.0 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1195-vmware_guest_network-remove_networks.yml
  changelogs/fragments/1196-vmware_host_firewall_manager-remove_deprecated_stuff.yml
  changelogs/fragments/1196-vsphere_copy-remove_deprecated_parameters.yml
  changelogs/fragments/1257-vmware_guest_boot_manager-remove_secure_boot_default.yml
  changelogs/fragments/1265-vmware_tag_manager-set_idempotency.yml
  changelogs/fragments/1268-vmware_vm_config_option-change_result.yml
  changelogs/fragments/1443-vmware_dvs_portgroup-update_netflow_not_work.yaml
  changelogs/fragments/1466-vmware_guest_disk-change_iolimit_without_size.yml
  changelogs/fragments/1483-vmware_dvs_portgroup.yml
  changelogs/fragments/3.0.0-required_ansible_version.yml
  changelogs/fragments/remove_deprecated_dns_config_module.yml
  changelogs/fragments/remove_deprecated_vca_modules.yml
  changelogs/fragments/remove_deprecated_vmware_guest_vnc_module.yml
  changelogs/fragments/vmware_dvs_portgroup-securityPolicy.yml
  changelogs/fragments/vmware_dvs_portgroup_info-securityPolicy.yml
  changelogs/fragments/vmware_dvswitch-securityPolicy.yml
  changelogs/fragments/vmware_dvswitch_uplink_pg-securityPolicyOverrideAllowed.yml
  changelogs/fragments/vmware_vspan_session-securityPolicy.yml
  docs/community.vmware.vca_fw_module.rst
  docs/community.vmware.vca_nat_module.rst
  docs/community.vmware.vca_vapp_module.rst
  docs/community.vmware.vmware_datastore_module.rst
  docs/community.vmware.vmware_guest_vnc_module.rst
  galaxy.yml
Labels: needs_triage, community_review, docs, mergeit

#1495 prepare 2.10.0 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1265-vmware_tag_manager-set_idempotency.yml
  changelogs/fragments/1443-vmware_dvs_portgroup-update_netflow_not_work.yaml
  changelogs/fragments/1466-vmware_guest_disk-change_iolimit_without_size.yml
  changelogs/fragments/1481-required_ansible_version.yml
  galaxy.yml
Labels: needs_info, needs_template, mergeit

#1496 Remove version 3.0.0 from galaxy.yml
  galaxy.yml
Labels: small_patch, mergeit

#1497 Remove version 2.10.0 from galaxy.yml
  galaxy.yml
Labels: small_patch, mergeit

#1504 Fixes #1503: vmware_tag_manager: Tag processing is very slow
  changelogs/fragments/1503-vmware_tag_manager-fix_performance_issue_during_tag_processing.yml
  plugins/module_utils/vmware_rest_client.py
  plugins/modules/vmware_tag_manager.py
Labels: bug, mergeit

#1507 Backport vmware_tag_manager: Tag processing is very slow
  changelogs/fragments/1503-vmware_tag_manager-fix_performance_issue_during_tag_processing.yml
  plugins/module_utils/vmware_rest_client.py
  plugins/modules/vmware_tag_manager.py
Labels: bug, mergeit

#1502 Fixes #1501: vmware_tag_manager: Changing the value of a single cardinal tag category fails with 'Tagging cardinality violation'
  changelogs/fragments/1501-vmware_tag_manager-Fix_failure_when_changing_single_cardinal_tag_category.yml
  plugins/modules/vmware_tag_manager.py
Labels: bug, mergeit

#1508 vmware_dvs_portgroup - Problem with securtiyPolicy and macManagement has not the same value
  changelogs/fragments/1508-vmware_dvs_portgroup.yaml
  plugins/modules/vmware_dvs_portgroup.py
Labels: mergeit

#1515 test-requirements: add pytest-fork
  test-requirements.txt
Labels: needs_triage, community_review, small_patch, mergeit

#1514 vmware_host_lockdown: Use current API
  changelogs/fragments/1514-vmware_host_lockdown-remove-deprecated-api-calls.yml
  plugins/modules/vmware_host_lockdown.py
  tests/integration/targets/vmware_host_lockdown/tasks/main.yml
Labels: mergeit

#1510 New module vmware_host_lockdown_exceptions
  plugins/modules/vmware_host_lockdown_exceptions.py
  tests/integration/targets/vmware_host_lockdown_exceptions/aliases
  tests/integration/targets/vmware_host_lockdown_exceptions/tasks/main.yml
Labels: module, feature, mergeit

#1513 vmware_guest_file_operation: add a new parameter for timeout
  changelogs/fragments/1323-vmware_guest_file_operation.yml
  plugins/modules/vmware_guest_file_operation.py
Labels: mergeit

#1519 Document 1.x as unmaintained
  README.md
Labels: community_review, docs, small_patch, mergeit

#1521 2.x test-requirements: add pytest-fork
  test-requirements.txt
Labels: community_review, small_patch, mergeit

#1520 2.x: Document 1.x as unmaintained
  README.md
Labels: community_review, docs, small_patch, mergeit

#1518 Remove version_added 1.x from doc_fragments in inventory
  docs/community.vmware.vmware_category_info_module.rst
  docs/community.vmware.vmware_category_module.rst
  docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
  docs/community.vmware.vmware_content_deploy_template_module.rst
  docs/community.vmware.vmware_content_library_info_module.rst
  docs/community.vmware.vmware_content_library_manager_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_object_rename_module.rst
  docs/community.vmware.vmware_tag_info_module.rst
  docs/community.vmware.vmware_tag_manager_module.rst
  docs/community.vmware.vmware_tag_module.rst
  docs/community.vmware.vmware_vc_infraprofile_info_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  plugins/doc_fragments/vmware_rest_client.py
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
Labels: community_review, inventory, docs, cloud, plugins, mergeit

#1527 prepare 2.10.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1501-vmware_tag_manager-Fix_failure_when_changing_single_cardinal_tag_category.yml
  changelogs/fragments/1503-vmware_tag_manager-fix_performance_issue_during_tag_processing.yml
  galaxy.yml
Labels: community_review, mergeit

#1528 Remove version 3.1.0 from galaxy.yml
  galaxy.yml
Labels: small_patch, mergeit

#1529 Remove version 2.10.1 from galaxy.yml
  galaxy.yml
Labels: small_patch, mergeit
