Repository ansible-collections/community.vmware, pull requests merged in 2022-01, with the labels that each got.

#1170 Fixed minor typos in scenario_clone_template.rst
  docs/docsite/rst/vmware_scenarios/scenario_clone_template.rst
Labels: gate

#1169 vmware_guest_network: Fix uncaught exception
  changelogs/fragments/25-vmware_guest_network-catch_taskerror.yml
  plugins/modules/vmware_guest_network.py
Labels: gate

#1080 Add support for configuring SR-IOV advanced options on a network interface in a VM
  changelogs/fragments/1080-add-sr-iov-advanced-options.yml
  plugins/module_utils/vm_device_helper.py
Labels: gate, needs_triage, community_review, feature

#1172 tests: disable vmware_content_library_manager for now
  tests/integration/targets/vmware_content_library_manager/aliases
Labels: gate

#1180 Revert "tests: disable vmware_content_library_manager for now (#1172)"
  tests/integration/targets/vmware_content_library_manager/aliases
Labels: gate

#1184 Change required ansible version to 2.11.0
  README.md
  changelogs/fragments/1182_ansible_version.yml
  meta/runtime.yml
Labels: mergeit

#1186 Remove ignores for non-supported ansible versions
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: mergeit

#1194 sanity: add two missing {compile,import}-2.6!skip
  plugins/modules/vmware_guest_network.py
  plugins/modules/vmware_host_firewall_manager.py
  plugins/modules/vsphere_copy.py
  tests/integration/targets/vmware_host_firewall_manager/tasks/main.yml
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
Labels: mergeit

#1191 Specify mutual exclusion of parameters
  plugins/modules/vmware_resource_pool.py
Labels: mergeit

#1193 tests/govcsim: ignore some broken tests
  tests/integration/targets/vmware_datastore_info/aliases
  tests/integration/targets/vmware_guest/aliases
  tests/integration/targets/vmware_guest_disk/aliases
  tests/integration/targets/vmware_host_scsidisk_info/aliases
Labels: mergeit

#1179 Add vmware_host_user_manager to manage the local user in ESXi
  docs/community.vmware.vmware_host_user_manager_module.rst
  plugins/modules/vmware_host_user_manager.py
  tests/integration/targets/vmware_host_user_manager/aliases
  tests/integration/targets/vmware_host_user_manager/tasks/main.yml
  tests/integration/targets/vmware_host_user_manager/tasks/operate_user_via_ESXi.yml
  tests/integration/targets/vmware_host_user_manager/tasks/operate_user_via_vcenter.yml
Labels: mergeit

#1143 add datastore_url to vm output from vm_info module
  changelogs/fragements/datastore_url-added-to-vm_info.yaml
  plugins/modules/vmware_vm_info.py
Labels: mergeit

#1171 vmware_vm_config_option: fix parameter not correct issue when connecting to ESXi host
  changelogs/fragments/vmware_vm_config_option.yml
  plugins/modules/vmware_vm_config_option.py
Labels: mergeit

#1200 backport vmware_guest_network: Fix uncaught exception and doc improvements
  changelogs/fragments/25-vmware_guest_network-catch_taskerror.yml
  plugins/modules/vmware_guest_network.py
  plugins/modules/vmware_host_firewall_manager.py
  plugins/modules/vmware_resource_pool.py
  plugins/modules/vsphere_copy.py
  tests/integration/targets/vmware_datastore_info/aliases
  tests/integration/targets/vmware_guest/aliases
  tests/integration/targets/vmware_guest_disk/aliases
Labels: mergeit

#1209 prepare 1.17.1 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/25-vmware_guest_network-catch_taskerror.yml
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_guest_network_module.rst
  docs/community.vmware.vmware_resource_pool_module.rst
Labels: needs_triage, community_review, docs, mergeit
