Repository ansible-collections/community.vmware, pull requests merged in 2022-05, with the labels that each got.

#1218 Add support for configuring SR-IOV advanced options on a network interface via vmware_guest_network
  changelogs/fragments/add-sriov-advanced-options-to-vmware_guest_network.yml
  plugins/module_utils/vm_device_helper.py
  plugins/modules/vmware_guest_network.py
Labels: mergeit

#1294 VCSIM removal part 4
  changelogs/fragments/1294-remove_vcsim.yml
  docs/docsite/extra-docs.yml
  docs/docsite/rst/dev_guide.rst
  docs/docsite/rst/vmware_scenarios/vmware_external_doc_links.rst
  plugins/modules/vmware_datastore_info.py
  plugins/modules/vmware_dvs_portgroup_info.py
  plugins/modules/vmware_guest.py
  testing.md
  tests/integration/cloud-config-vcenter.ini.sample
Labels: docs, mergeit

#1304 prepare_release.yml: only commit changes is needed
  tools/prepare_release.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1305 vmware_migrate_vmk: Add VLAN parameter
  changelogs/fragments/1297-vmware_migrate_vmk-add_vlan.yml
  plugins/modules/vmware_migrate_vmk.py
Labels: feature, mergeit

#1306 Prepare for distutils.version being removed in Python 3.12
  changelogs/fragments/disutils.version.yml
  plugins/module_utils/version.py
  plugins/module_utils/vmware.py
Labels: bug, python3, community_review, has_issue, module_utils, plugins, mergeit

#1307 Fix sanity tests for ansible-core 2.13
  tests/sanity/ignore-2.13.txt
Labels: bug, community_review, tests, small_patch, mergeit

#1308 make dev guide anchor unique
  docs/docsite/rst/dev_guide.rst
Labels: community_review, docs, small_patch, mergeit

#1298 Update vmware_vswitch to support policies
  changelogs/fragments/1298-vmware_vswitch-add_network_policy_support.yml
  plugins/modules/vmware_vswitch.py
  tests/integration/targets/vmware_vswitch/tasks/main.yml
Labels: mergeit

#1309 vmware_vswitch_info: Add support to return information about policies
  changelogs/fragments/1309-vmware_vswitch_info-add_network_policy_support.yml
  plugins/modules/vmware_vswitch_info.py
  tests/integration/targets/vmware_vswitch_info/tasks/main.yml
Labels: feature, mergeit

#1311 vmware_maintenancemode: Add support for check_mode
  changelogs/fragments/1311-vmware_maintenancemode-check_mode.yml
  plugins/modules/vmware_maintenancemode.py
Labels: feature, mergeit

#1310 Add a documentation example for selecting a specific NIC
  plugins/inventory/vmware_vm_inventory.py
Labels: community_review, has_issue, inventory, docs, cloud, plugins, mergeit

#1313 prepare 2.4.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1297-vmware_migrate_vmk-add_vlan.yml
  changelogs/fragments/1298-vmware_vswitch-add_network_policy_support.yml
  changelogs/fragments/1309-vmware_vswitch_info-add_network_policy_support.yml
  changelogs/fragments/1311-vmware_maintenancemode-check_mode.yml
  changelogs/fragments/disutils.version.yml
  docs/community.vmware.vmware_migrate_vmk_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  docs/community.vmware.vmware_vswitch_info_module.rst
  docs/community.vmware.vmware_vswitch_module.rst
Labels: community_review, docs, mergeit

#1315 move check-ignores-order in tools/
  tools/check-ignores-order
  tox.ini
Labels: needs_info, needs_template, mergeit

#1283 vmware_vm_info: Add allocated Storage, CPU and Memory to output
  changelogs/fragments/1283-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
  plugins/modules/vmware_vm_info.py
Labels: mergeit

#1320 Add version to galaxy.yml
  README.md
  galaxy.yml
  tools/prepare_release.yml
Labels: community_review, feature, mergeit

#1324 Add playbook to revert version to null
  README.md
  tools/unset_version.yml
Labels: community_review, feature, mergeit

#1325 prepare 2.5.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1283-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
  galaxy.yml
Labels: needs_info, needs_template, mergeit

#1326 Remove version 2.5.0 from galaxy.yml
  galaxy.yml
Labels: community_review, docs, small_patch, mergeit

#1327 galaxy.yml: Mover version below comment
  galaxy.yml
Labels: community_review, docs, small_patch, mergeit

#1240 vmware_vmotion: Add cluster and datastore cluster
  changelogs/fragments/1240-vmware_vmotion-add_cluster_storage_cluster.yaml
  plugins/modules/vmware_vmotion.py
Labels: mergeit

#1329 vmware_host_facts: Fix module when host is disconnected
  changelogs/fragments/184_vmware_host_facts.yml
  plugins/modules/vmware_host_facts.py
  tests/integration/targets/vmware_host_facts/aliases
  tests/integration/targets/vmware_host_facts/tasks/main.yml
Labels: mergeit

#1336 Fix some sanity and lint issues
  docs/docsite/rst/dev_guide.rst
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
Labels: bug, community_review, tests, docs, mergeit
