Repository ansible-collections/community.vmware, pull requests merged in 2022-11, with the labels that each got.

#1523 vmware_dvs_portgroup: Fix deleting portgroups
  changelogs/fragments/1522-vmware_dvs_portgroup.yml
  plugins/modules/vmware_dvs_portgroup.py
Labels: bug, mergeit

#1524 2.x: vmware_dvs_portgroup: Fix deleting portgroups
  changelogs/fragments/1522-vmware_dvs_portgroup.yml
  plugins/modules/vmware_dvs_portgroup.py
Labels: bug, mergeit

#1530 Fix non-matching defaults in docs
  plugins/modules/vcenter_standard_key_provider.py
  plugins/modules/vmware_content_library_manager.py
  plugins/modules/vmware_dvs_host.py
  plugins/modules/vmware_dvswitch_lacp.py
  plugins/modules/vmware_dvswitch_nioc.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_sendkey.py
  plugins/modules/vmware_host_active_directory.py
  plugins/modules/vmware_host_snmp.py
Labels: documentation, mergeit

#1531 2.x: Fix non-matching defaults in docs
  plugins/modules/vcenter_standard_key_provider.py
  plugins/modules/vmware_content_library_manager.py
  plugins/modules/vmware_dvs_host.py
  plugins/modules/vmware_dvswitch_lacp.py
  plugins/modules/vmware_dvswitch_nioc.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_network.py
  plugins/modules/vmware_guest_sendkey.py
  plugins/modules/vmware_host_active_directory.py
  plugins/modules/vmware_host_snmp.py
Labels: documentation, mergeit

#1532 vmware_guest_custom_attributes: Improve the code quality and add the return value for the diff
  changelogs/fragments/1532-vmware_guest_custom_attributes.yml
  plugins/modules/vmware_guest_custom_attributes.py
  tests/integration/targets/vmware_guest_custom_attributes/tasks/main.yml
Labels: mergeit

#1540 vmware_host_lockdown: VmwareLockdownManager object has no attribute warn
  changelogs/fragments/1540-vmware_host_lockdown.yml
  plugins/modules/vmware_host_lockdown.py
Labels: bug, mergeit

#1536 Generic modules for custom attributes
  meta/runtime.yml
  plugins/modules/vmware_custom_attribute.py
  plugins/modules/vmware_custom_attribute_manager.py
  tests/integration/targets/vmware_custom_attribute/aliases
  tests/integration/targets/vmware_custom_attribute/tasks/main.yml
  tests/integration/targets/vmware_custom_attribute_manager/aliases
  tests/integration/targets/vmware_custom_attribute_manager/tasks/main.yml
Labels: feature, has_issue, new_module, mergeit

#1539 vmware_guest.py - Add CPU/MEM shares support on guest
  changelogs/fragments/1539-vmware_guest_shares.yml
  plugins/modules/vmware_guest.py
  tests/integration/targets/vmware_guest/defaults/main.yml
  tests/integration/targets/vmware_guest/tasks/shares.yml
Labels: feature, has_issue, mergeit

#1548 Backport vmware_portgroup_info fix
  changelogs/fragments/1544-vmware_portgroup_info.yml
  plugins/modules/vmware_portgroup_info.py
Labels: bug, mergeit

#1543 vmware_guest_boot_manager: Add a new parameter 'boot_hdd_name' to specify the boot disk name
  changelogs/fragments/1543-vmware_guest_boot_manager.yml
  plugins/modules/vmware_guest_boot_manager.py
  tests/integration/targets/vmware_guest_boot_manager/tasks/main.yml
Labels: feature, mergeit

#1551 Add resource pool of vm to vm_info output
  changelogs/fragments/1511-vmware_vm_info.yml
  plugins/modules/vmware_vm_info.py
Labels: feature, mergeit

#1552 vmware_guest: Add vPMC support
  changelogs/fragments/1511-vmware_guest-vpmc.yml
  plugins/modules/vmware_guest.py
Labels: feature, has_issue, mergeit

#1541 vmware_object_custom_attributes_info: Support the global type of custom attribute
  changelogs/fragments/1541-vmware_object_custom_attributes_info.yml
  plugins/modules/vmware_object_custom_attributes_info.py
  tests/integration/targets/vmware_object_custom_attributes_info/tasks/cleanup.yml
  tests/integration/targets/vmware_object_custom_attributes_info/tasks/main.yml
  tests/integration/targets/vmware_object_custom_attributes_info/tasks/pre.yml
  tests/integration/targets/vmware_object_custom_attributes_info/tasks/vmware_object_custom_attributes_info_tests.yml
Labels: bug, has_issue, mergeit

#1557 vmware_guest_instant_clone: Fix an issue with pyVmomi 8.0.0.1
  changelogs/fragments/1555-vmware_guest_instant_clone-pyvmomi_8_0_0_1.yml
  plugins/module_utils/vmware.py
Labels: bug, community_review, has_issue, module_utils, plugins, small_patch, mergeit

#1559 2.x: vmware_guest_instant_clone: Fix an issue with pyVmomi 8.0.0.1
  changelogs/fragments/1555-vmware_guest_instant_clone-pyvmomi_8_0_0_1.yml
  plugins/module_utils/vmware.py
Labels: bug, community_review, module_utils, plugins, small_patch, mergeit

#1560 2.x: vmware_object_custom_attributes_info: Global custom attributes
  changelogs/fragments/1477-vmware_object_custom_attributes_info.yml
  plugins/modules/vmware_object_custom_attributes_info.py
Labels: bug, mergeit
