Repository ansible-collections/community.vmware, pull requests merged in 2022-07, with the labels that each got.

#1355 vmware_cluster_vCLS - Override default vCLS
  plugins/modules/vmware_cluster_vcls.py
Labels: new_module, mergeit

#1354 vmware_guest_instant_clone: Support FQPN of folder path
  changelogs/fragments/1354-vmware_guest_instant_clone.yml
  plugins/modules/vmware_guest_instant_clone.py
Labels: mergeit

#1382 Add support vPMem disk config in vmware_guest_disk module
  changelogs/fragments/1382-vmware_guest_disk.yml
  plugins/modules/vmware_guest_disk.py
Labels: mergeit

#1352 vmware_dvswitch - Add Netflow Settings
  changelogs/fragments/1352-vmaware_dvswitch.yaml
  plugins/modules/vmware_dvswitch.py
Labels: feature, mergeit

#1376 vmware_guest_sendkey: Add CTRL_X support
  changelogs/fragments/1376-vmware_guest_sendkey-add-ctrl_x-support.yaml
  plugins/modules/vmware_guest_sendkey.py
Labels: feature, mergeit

#1389 vmware_cfg_backup: Add integration tests
  tests/integration/targets/vmware_cfg_backup/aliases
  tests/integration/targets/vmware_cfg_backup/tasks/main.yml
Labels: integration, tests, mergeit

#1394 vmware_cfg_backup: Add integration test without vCenter
  tests/integration/targets/vmware_cfg_backup/tasks/main.yml
Labels: integration, tests, mergeit

#1397 Prepare adding SPDX-License-Identifier
  LICENSES/GPL-3.0-or-later.txt
Labels: community_review, docs, mergeit

#1402 vmware_guest: change fail to fail_json function
  changelogs/fragments/1402-vmware_guest_change_to_fail_json.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#1392 Proposed fixes for backup behavior #1383
  changelogs/fragments/1392-proposed_fixes_for_backup_behavior_1383.yml
  plugins/modules/vmware_cfg_backup.py
Labels: mergeit

#1408 vmware_vm_info: Fix NoneType object has no attribute datastoreUrl for inaccessible VMs
  changelogs/fragments/1407-vmware_vm_info-inaccessible_vm.yml
  plugins/modules/vmware_vm_info.py
Labels: bug, has_issue, mergeit

#1413 require Python 3.8+ and Ansibe 2.12
  README.md
  tests/config.yml
  tests/sanity/ignore-2.12.txt
Labels: python3, community_review, tests, mergeit
