Repository ansible-collections/community.vmware, pull requests merged in 2022-04, with the labels that each got.

#1224 vmware_dvs_portgroup: ingress and egress traffic shaping and netFlow
  changelogs/fragments/1224-vmware_dvs_portgroup-ingress_egress_traffic_shaping_and_netflow.yaml
  plugins/modules/vmware_dvs_portgroup.py
Labels: feature, mergeit

#1236 Bugfix vmware_vmotion: Only Storage vmotion
  changelogs/fragments/1236-vmware_vmotion-svmotion_without_resourcepool.yml
  plugins/modules/vmware_vmotion.py
Labels: mergeit

#1276 vmware_guest_powerstate: Use FQCN in examples
  plugins/modules/vmware_guest_powerstate.py
Labels: mergeit

#1280 vmware_guest_powerstate: Ignore trailing slash in folder parameter
  changelogs/fragments/1238-vmware_guest_powerstate-ignore_trailing_slash_in_folder.yml
  plugins/modules/vmware_guest_powerstate.py
  tests/integration/targets/vmware_guest_powerstate/tasks/main.yml
Labels: bug, integration, mergeit

#1286 vmware_dvs_portgroup: Fix idempotency
  changelogs/fragments/1286-vmware_dvs_portgroup-fix_idempotency.yml
  plugins/modules/vmware_dvs_portgroup.py
Labels: bug, mergeit

#1293 VCSIM removal part 3
  tests/integration/targets/prepare_vmware_tests/defaults/main.yml
  tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim.yml
  tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim_with_container.yml
  tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim_with_systemd.yml
  tests/integration/targets/prepare_vmware_tests/tasks/main.yml
  tests/integration/targets/prepare_vmware_tests/tasks/teardown.yml
  tests/integration/targets/prepare_vmware_tests/vars/vcsim.yml
  tests/integration/targets/vmware_guest/defaults/main.yml
  tests/integration/targets/vmware_guest/tasks/clone_d1_c1_f0.yml
  tests/integration/targets/vmware_guest/tasks/create_d1_c1_f0.yml
  tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
  tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
  tests/integration/targets/vmware_guest/tasks/template_d1_c1_f0.yml
Labels: mergeit

#1279 add vmware_cluster_dpm.py
  plugins/modules/vmware_cluster_dpm.py
  tests/integration/targets/vmware_cluster_dpm/aliases
  tests/integration/targets/vmware_cluster_dpm/tasks/main.yml
Labels: mergeit

#1299 vmware_host_powerstate: Do not execute the tasks in check mode
  changelogs/fragments/1299-vnware_host_powerstate-fix_check_mode.yml
  plugins/modules/vmware_host_powerstate.py
Labels: mergeit
