Repository ansible-collections/community.vmware, pull requests merged in 2023-09, with the labels that each got.

#1836 Fix typo in Docs for vmware_guest module
  plugins/modules/vmware_guest.py
Labels: documentation, mergeit

#1837 feat: add feature to allow template username and password on inventory
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_host_graphics_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
Labels: mergeit

#1833 Added module for managing password expiration for root user
  plugins/modules/vcenter_root_password_expiration.py
Labels: new_module, mergeit

#1840 meta/runtime.yml: Add missing modules
  meta/runtime.yml
Labels: mergeit
