Repository ansible-collections/community.vmware, pull requests merged in 2023-02, with the labels that each got.

#1619 20230203 Fix pylint issues
  changelogs/fragments/1618_pylint.yml
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_dvswitch_lacp.py
  plugins/modules/vmware_dvswitch_uplink_pg.py
  plugins/modules/vmware_portgroup.py
  plugins/modules/vmware_vcenter_settings.py
  plugins/modules/vmware_vcenter_statistics.py
  tests/unit/module_utils/test_vmware.py
Labels: bug, CI, mergeit

#1622 Backport 1619: Fix pylint issues
  changelogs/fragments/1618_pylint.yml
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_dvswitch_lacp.py
  plugins/modules/vmware_dvswitch_uplink_pg.py
  plugins/modules/vmware_portgroup.py
  plugins/modules/vmware_vcenter_settings.py
  plugins/modules/vmware_vcenter_statistics.py
  tests/unit/module_utils/test_vmware.py
Labels: bug, CI, mergeit

#1616 vmware_guest_disk: add IDE disk support
  changelogs/fragments/1616-vmware_guest_disk.yml
  plugins/module_utils/vm_device_helper.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_disk_info.py
  tests/integration/targets/vmware_guest_disk/tasks/main.yml
Labels: feature, mergeit

#1624 tools/create_documentation_tasks: Improve task name
  tools/create_documentation_tasks.yml
Labels: community_review, docs, small_patch, mergeit

#1623 Fix wrong key in the documentation of the return values
  changelogs/fragments/1615-wrong_key_for_return_value.yml
  docs/community.vmware.vmware_guest_disk_module.rst
  plugins/modules/vmware_guest_disk.py
Labels: bug, documentation, docs, mergeit

#1625 Backport tools/create_documentation_tasks: Improve task name
  tools/create_documentation_tasks.yml
Labels: community_review, docs, small_patch, mergeit

#1626 Backport Fix wrong key in the documentation of the return values
  changelogs/fragments/1615-wrong_key_for_return_value.yml
  docs/community.vmware.vmware_guest_disk_module.rst
  plugins/modules/vmware_guest_disk.py
Labels: bug, documentation, docs, mergeit

#1627 Issue 1606 Fix vmware_guest_custom_attributes failing on new VMs with KeyError 'value'
  changelogs/fragments/1606-vmware_guest_custom_attributes.yml
  plugins/modules/vmware_guest_custom_attributes.py
Labels: bug, has_issue, mergeit

#1634 Add missing quotation mark to error message
  changelogs/fragments/1633-missing_quotation_mark.yml
  plugins/modules/vmware_object_rename.py
Labels: bug, mergeit

#1637 Remove unneccessary imports
  changelogs/fragments/1637-pylint-issues.yml
  plugins/module_utils/version.py
  plugins/module_utils/vmware_rest_client.py
  scripts/inventory/vmware.py
  tests/unit/compat/builtins.py
Labels: bug, inventory, module_utils, tests, cloud, plugins, mergeit

#1638 2.x: Remove unneccessary imports
  changelogs/fragments/1638-pylint-issues.yml
  plugins/module_utils/version.py
  plugins/module_utils/vmware_rest_client.py
  scripts/inventory/vmware.py
  tests/unit/compat/builtins.py
Labels: bug, inventory, module_utils, tests, cloud, plugins, mergeit

#1641 Extend return value documentation for vmware_guest_disk
  changelogs/fragments/1641_extend_result_docs_guest_disk
  plugins/modules/vmware_guest_disk.py
Labels: docs, mergeit

#1629 vmware_vmotion: Add timeout parameter
  changelogs/fragments/1629-vmware_vmotion.yml
  plugins/modules/vmware_vmotion.py
Labels: feature, mergeit

#1643 vmware_vm_inventory: add example for groups parameter
  plugins/inventory/vmware_vm_inventory.py
Labels: docs, mergeit

#1649 prepare 3.4.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1606-vmware_guest_custom_attributes.yml
  changelogs/fragments/1610-scenario_guides.yml
  changelogs/fragments/1615-wrong_key_for_return_value.yml
  changelogs/fragments/1616-vmware_guest_disk.yml
  changelogs/fragments/1618_pylint.yml
  changelogs/fragments/1629-vmware_vmotion.yml
  changelogs/fragments/1633-missing_quotation_mark.yml
  changelogs/fragments/1637-pylint-issues.yml
  changelogs/fragments/1641_extend_result_docs_guest_disk
  docs/community.vmware.vmware_guest_disk_module.rst
  docs/community.vmware.vmware_host_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  docs/community.vmware.vmware_vmotion_module.rst
  galaxy.yml
Labels: mergeit

#1650 prepare 2.10.4 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1610-scenario_guides.yml
  changelogs/fragments/1615-wrong_key_for_return_value.yml
  changelogs/fragments/1618_pylint.yml
  changelogs/fragments/1638-pylint-issues.yml
  galaxy.yml
Labels: mergeit

#1651 Remove version 3.4.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1652 Remove version 2.10.4 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1656 Fix changelog
  CHANGELOG.rst
Labels: mergeit
