Repository ansible-collections/community.vmware, pull requests merged in 2023-03, with the labels that each got.

#1653 fixing ssl validation behaviour
  changelogs/fragments/1653-cross_vc_clone_ssl_thumbprint.yml
  plugins/modules/vmware_guest_cross_vc_clone.py
Labels: bug, mergeit

#1605 Improve tag processing performance and allow to use category names for tag management
  changelogs/fragments/1603-fix_tagging_performance_issue.yml
  changelogs/fragments/1614-allow_to_use_category_names_for_tag_management.yml
  plugins/module_utils/vmware_rest_client.py
  plugins/modules/vmware_tag.py
  plugins/modules/vmware_tag_manager.py
  plugins/modules/vmware_vm_storage_policy.py
Labels: mergeit

#1661 Use false instead of no in examples
  changelogs/fragments/1660-false_instead_no_examples.yml
  docs/community.vmware.vmware_deploy_ovf_module.rst
  docs/community.vmware.vmware_guest_disk_module.rst
  docs/community.vmware.vmware_guest_file_operation_module.rst
  docs/community.vmware.vmware_guest_storage_policy_module.rst
  docs/community.vmware.vmware_guest_vgpu_info_module.rst
  docs/community.vmware.vmware_guest_vgpu_module.rst
  docs/community.vmware.vmware_host_datastore_module.rst
  docs/community.vmware.vmware_recommended_datastore_module.rst
  plugins/modules/vmware_deploy_ovf.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_file_operation.py
  plugins/modules/vmware_guest_storage_policy.py
  plugins/modules/vmware_guest_vgpu.py
  plugins/modules/vmware_guest_vgpu_info.py
  plugins/modules/vmware_host_datastore.py
  plugins/modules/vmware_recommended_datastore.py
Labels: documentation, docs, mergeit

#1647 adds uuid support for vmware_tools connection plugin
  changelogs/fragments/1647-uuid_vmware_tools_connections.yml
  plugins/connection/vmware_tools.py
Labels: feature, mergeit

#1657 vmware_guest: fix adding nvdimm device issue on ESXi host
  changelogs/1657-vmware_guest.yml
  plugins/module_utils/vm_device_helper.py
  plugins/modules/vmware_guest.py
Labels: bug, has_issue, mergeit

#1665 Issue1660 2
  changelogs/fragments/1660-false_instead_no_examples.yml
  docs/community.vmware.vcenter_standard_key_provider_module.rst
  docs/community.vmware.vmware_cluster_drs_module.rst
  docs/community.vmware.vmware_cluster_ha_module.rst
  docs/community.vmware.vmware_cluster_info_module.rst
  docs/community.vmware.vmware_cluster_vsan_module.rst
  docs/community.vmware.vmware_datacenter_info_module.rst
  docs/community.vmware.vmware_datastore_cluster_module.rst
  docs/community.vmware.vmware_dvs_portgroup_module.rst
  docs/community.vmware.vmware_dvswitch_module.rst
  docs/community.vmware.vmware_dvswitch_uplink_pg_module.rst
  docs/community.vmware.vmware_guest_boot_manager_module.rst
  docs/community.vmware.vmware_guest_disk_module.rst
  docs/community.vmware.vmware_guest_file_operation_module.rst
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_tag_manager_module.rst
  docs/community.vmware.vmware_tag_module.rst
  docs/community.vmware.vmware_tools_connection.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
  plugins/modules/vcenter_standard_key_provider.py
  plugins/modules/vmware_cluster_drs.py
  plugins/modules/vmware_cluster_ha.py
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_cluster_vsan.py
  plugins/modules/vmware_datacenter_info.py
  plugins/modules/vmware_datastore_cluster.py
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_dvswitch_uplink_pg.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_boot_manager.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_file_operation.py
Labels: documentation, mergeit

#1666 Issue 1660 part 3
  docs/community.vmware.vmware_guest_info_module.rst
  docs/community.vmware.vmware_guest_instant_clone_module.rst
  docs/community.vmware.vmware_guest_powerstate_module.rst
  docs/community.vmware.vmware_guest_serial_port_module.rst
  docs/community.vmware.vmware_host_facts_module.rst
  docs/community.vmware.vmware_host_firewall_manager_module.rst
  docs/community.vmware.vmware_host_module.rst
  docs/community.vmware.vmware_portgroup_module.rst
  docs/community.vmware.vmware_vm_config_option_module.rst
  docs/community.vmware.vmware_vm_host_drs_rule_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  docs/community.vmware.vmware_vm_shell_module.rst
  docs/community.vmware.vmware_vm_vm_drs_rule_module.rst
  docs/community.vmware.vmware_vmkernel_module.rst
  docs/community.vmware.vmware_vsan_health_info_module.rst
  docs/community.vmware.vmware_vspan_session_module.rst
  docs/community.vmware.vmware_vswitch_module.rst
  plugins/inventory/vmware_vm_inventory.py
  plugins/modules/vmware_guest_info.py
  plugins/modules/vmware_guest_instant_clone.py
  plugins/modules/vmware_guest_powerstate.py
  plugins/modules/vmware_guest_serial_port.py
  plugins/modules/vmware_host.py
  plugins/modules/vmware_host_facts.py
  plugins/modules/vmware_host_firewall_manager.py
  plugins/modules/vmware_host_service_manager.py
  plugins/modules/vmware_portgroup.py
  plugins/modules/vmware_vm_config_option.py
  plugins/modules/vmware_vm_host_drs_rule.py
  plugins/modules/vmware_vm_shell.py
  plugins/modules/vmware_vm_vm_drs_rule.py
  plugins/modules/vmware_vmkernel.py
  plugins/modules/vmware_vsan_health_info.py
  plugins/modules/vmware_vspan_session.py
  plugins/modules/vmware_vswitch.py
Labels: documentation, mergeit

#1668 Issue 1660 part 4
  docs/community.vmware.vmware_host_service_manager_module.rst
  plugins/connection/vmware_tools.py
  plugins/doc_fragments/vmware.py
  plugins/doc_fragments/vmware_rest_client.py
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
  plugins/modules/vcenter_domain_user_group_info.py
  plugins/modules/vcenter_extension.py
  plugins/modules/vcenter_folder.py
  plugins/modules/vcenter_standard_key_provider.py
  plugins/modules/vmware_category.py
  plugins/modules/vmware_cfg_backup.py
  plugins/modules/vmware_cluster_drs.py
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_content_deploy_ovf_template.py
  plugins/modules/vmware_content_deploy_template.py
  plugins/modules/vmware_content_library_info.py
  plugins/modules/vmware_content_library_manager.py
  plugins/modules/vmware_custom_attribute.py
  plugins/modules/vmware_custom_attribute_manager.py
  plugins/modules/vmware_datacenter.py
  plugins/modules/vmware_datacenter_info.py
  plugins/modules/vmware_datastore.py
  plugins/modules/vmware_datastore_cluster.py
  plugins/modules/vmware_datastore_cluster_manager.py
  plugins/modules/vmware_datastore_info.py
  plugins/modules/vmware_datastore_maintenancemode.py
  plugins/modules/vmware_deploy_ovf.py
  plugins/modules/vmware_dvs_host.py
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_dvs_portgroup_find.py
  plugins/modules/vmware_dvs_portgroup_info.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_dvswitch_info.py
  plugins/modules/vmware_dvswitch_lacp.py
  plugins/modules/vmware_dvswitch_nioc.py
  plugins/modules/vmware_dvswitch_pvlans.py
  plugins/modules/vmware_dvswitch_uplink_pg.py
  plugins/modules/vmware_evc_mode.py
  plugins/modules/vmware_first_class_disk.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_cross_vc_clone.py
  plugins/modules/vmware_guest_custom_attribute_defs.py
  plugins/modules/vmware_guest_custom_attributes.py
  plugins/modules/vmware_guest_customization_info.py
  plugins/modules/vmware_guest_disk_info.py
Labels: documentation, mergeit

#1669 Issue 1660 part 5
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_file_operation.py
  plugins/modules/vmware_guest_info.py
  plugins/modules/vmware_guest_instant_clone.py
  plugins/modules/vmware_guest_move.py
  plugins/modules/vmware_guest_network.py
  plugins/modules/vmware_guest_powerstate.py
  plugins/modules/vmware_guest_register_operation.py
  plugins/modules/vmware_guest_serial_port.py
  plugins/modules/vmware_guest_snapshot.py
  plugins/modules/vmware_guest_snapshot_info.py
  plugins/modules/vmware_guest_tools_upgrade.py
  plugins/modules/vmware_guest_vgpu.py
  plugins/modules/vmware_guest_vgpu_info.py
  plugins/modules/vmware_host.py
  plugins/modules/vmware_host_acceptance.py
  plugins/modules/vmware_host_auto_start.py
  plugins/modules/vmware_host_custom_attributes.py
  plugins/modules/vmware_host_datastore.py
  plugins/modules/vmware_host_facts.py
  plugins/modules/vmware_host_firewall_manager.py
  plugins/modules/vmware_host_iscsi.py
  plugins/modules/vmware_host_iscsi_info.py
  plugins/modules/vmware_host_lockdown_exceptions.py
  plugins/modules/vmware_host_logbundle.py
  plugins/modules/vmware_host_logbundle_info.py
  plugins/modules/vmware_host_ntp.py
  plugins/modules/vmware_host_passthrough.py
  plugins/modules/vmware_host_powerstate.py
  plugins/modules/vmware_host_service_manager.py
  plugins/modules/vmware_host_sriov.py
  plugins/modules/vmware_local_role_manager.py
  plugins/modules/vmware_local_user_manager.py
  plugins/modules/vmware_maintenancemode.py
  plugins/modules/vmware_migrate_vmk.py
  plugins/modules/vmware_object_custom_attributes_info.py
  plugins/modules/vmware_object_rename.py
  plugins/modules/vmware_object_role_permission.py
  plugins/modules/vmware_object_role_permission_info.py
  plugins/modules/vmware_portgroup.py
  plugins/modules/vmware_recommended_datastore.py
  plugins/modules/vmware_resource_pool.py
  plugins/modules/vmware_tag_manager.py
Labels: documentation, mergeit

#1671 Issue 1660 part 6
  plugins/doc_fragments/vmware_rest_client.py
  plugins/inventory/vmware_vm_inventory.py
  plugins/modules/vcenter_domain_user_group_info.py
  plugins/modules/vmware_cluster_drs.py
  plugins/modules/vmware_cluster_ha.py
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_cluster_vsan.py
  plugins/modules/vmware_content_library_manager.py
  plugins/modules/vmware_datacenter_info.py
  plugins/modules/vmware_datastore_info.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_boot_manager.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_info.py
  plugins/modules/vmware_guest_video.py
  plugins/modules/vmware_host.py
  plugins/modules/vmware_host_facts.py
  plugins/modules/vmware_local_role_manager.py
  plugins/modules/vmware_maintenancemode.py
  plugins/modules/vmware_tag.py
  plugins/modules/vmware_target_canonical_info.py
  plugins/modules/vmware_vc_infraprofile_info.py
  plugins/modules/vmware_vcenter_settings.py
  plugins/modules/vmware_vcenter_statistics.py
  plugins/modules/vmware_vm_config_option.py
  plugins/modules/vmware_vm_host_drs_rule.py
  plugins/modules/vmware_vm_info.py
  plugins/modules/vmware_vm_shell.py
  plugins/modules/vmware_vm_storage_policy.py
  plugins/modules/vmware_vm_vm_drs_rule.py
  plugins/modules/vmware_vm_vss_dvs_migrate.py
  plugins/modules/vmware_vmkernel.py
  plugins/modules/vmware_vsan_cluster.py
  plugins/modules/vmware_vsan_health_info.py
  plugins/modules/vmware_vspan_session.py
  plugins/modules/vmware_vswitch.py
Labels: documentation, mergeit

#1673 Issue 1660 part 7
  changelogs/fragments/1657-vmware_guest.yml
  changelogs/fragments/1660_truthy.yml
  docs/community.vmware.vcenter_domain_user_group_info_module.rst
  docs/community.vmware.vmware_category_info_module.rst
  docs/community.vmware.vmware_category_module.rst
  docs/community.vmware.vmware_cluster_drs_module.rst
  docs/community.vmware.vmware_cluster_ha_module.rst
  docs/community.vmware.vmware_cluster_info_module.rst
  docs/community.vmware.vmware_cluster_vsan_module.rst
  docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
  docs/community.vmware.vmware_content_deploy_template_module.rst
  docs/community.vmware.vmware_content_library_info_module.rst
  docs/community.vmware.vmware_content_library_manager_module.rst
  docs/community.vmware.vmware_datacenter_info_module.rst
  docs/community.vmware.vmware_datastore_info_module.rst
  docs/community.vmware.vmware_guest_boot_manager_module.rst
  docs/community.vmware.vmware_guest_controller_module.rst
  docs/community.vmware.vmware_guest_disk_module.rst
  docs/community.vmware.vmware_guest_info_module.rst
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_guest_video_module.rst
  docs/community.vmware.vmware_host_facts_module.rst
  docs/community.vmware.vmware_host_module.rst
  docs/community.vmware.vmware_local_role_manager_module.rst
  docs/community.vmware.vmware_maintenancemode_module.rst
  docs/community.vmware.vmware_object_rename_module.rst
  docs/community.vmware.vmware_tag_info_module.rst
  docs/community.vmware.vmware_tag_manager_module.rst
  docs/community.vmware.vmware_tag_module.rst
  docs/community.vmware.vmware_vc_infraprofile_info_module.rst
  docs/community.vmware.vmware_vm_config_option_module.rst
  docs/community.vmware.vmware_vm_host_drs_rule_module.rst
  docs/community.vmware.vmware_vm_info_module.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  docs/community.vmware.vmware_vm_shell_module.rst
  docs/community.vmware.vmware_vm_vm_drs_rule_module.rst
  docs/community.vmware.vmware_vsan_health_info_module.rst
Labels: documentation, mergeit

#1675 vmware_vsan_hcl_db: Add initial module
  plugins/modules/vmware_vsan_hcl_db.py
Labels: mergeit

#1676 Module vmware_guest_cross_vc_clone - fix timeout and notauthenticated issue
  changelogs/fragments/1223-cross_vc_clone_timeout.yml
  plugins/modules/vmware_guest_cross_vc_clone.py
Labels: mergeit

#1685 Add missing version_added and fix changelog fragment
  changelogs/fragments/1223-cross_vc_clone_timeout.yml
  plugins/modules/vmware_guest_cross_vc_clone.py
  plugins/modules/vmware_vmotion.py
Labels: mergeit

#1686 vmware_migrate_vmk: Enable integration tests again
  changelogs/fragments/1118-vmware_migrate_vmk.yml
  plugins/modules/vmware_migrate_vmk.py
  tests/integration/targets/vmware_migrate_vmk/aliases
  tests/integration/targets/vmware_migrate_vmk/tasks/main.yml
Labels: CI, has_issue, mergeit

#1683 issue_1682_vmware_vm_info_more_show_parameters
  changelogs/fragments/1682_vmware_vm_info
  plugins/modules/vmware_vm_info.py
Labels: feature, has_issue, mergeit

#1691 Remove version 3.5.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1687 vmware_host_tcpip_stacks: Enable integration tests again
  tests/integration/targets/vmware_host_tcpip_stacks/aliases
  tests/integration/targets/vmware_host_tcpip_stacks/tasks/main.yml
  tests/integration/targets/vmware_host_tcpip_stacks/tasks/post.yml
  tests/integration/targets/vmware_host_tcpip_stacks/tasks/pre.yml
  tests/integration/targets/vmware_host_tcpip_stacks/tasks/vmware_host_tcpip_stacks_tests.yml
Labels: CI, has_issue, mergeit
