Repository ansible-collections/community.vmware, pull requests merged in 2023-07, with the labels that each got.

#1791 Use antsibull-docs to create documentation
  tools/antsibull-docs-wrapper.sh
  tools/create_documentation_tasks.yml
Labels: documentation, community_review, docs, mergeit

#1797 prepare 3.8.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1590_vmware_deploy_ovf.yaml
  changelogs/fragments/1751-autoselect_datastore-also-use-NFS-mounts.yml
  changelogs/fragments/1765_vmware_guest_disk.yaml
  changelogs/fragments/1774_vmware_vasa.yaml
  changelogs/fragments/1774_vmware_vasa_info.yaml
  galaxy.yml
  tools/antsibull-docs-wrapper.sh
Labels: needs_template, mergeit

#1798 Remove version 3.8.0 from galaxy.yml
  galaxy.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1779 Implement encryption configuration for vm vmotion and ft
  changelogs/fragments/1069_vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: feature, has_issue, mergeit

#1813 vmware_dvswitch_uplink_pg: Fix typo
  plugins/modules/vmware_dvswitch_uplink_pg.py
Labels: documentation, has_issue, mergeit

#1814 vmware_vm_info: Add instance_uuid
  changelogs/fragments/1805_vmware_vm_info.yml
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_vm_info.py
Labels: CI, feature, has_issue, mergeit

#1816 stable-2.x: Fix linter errors
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_guest_disk.py
Labels: CI, mergeit

#1777 Added vvols to the managed datastore types
  changelogs/fragments/1777-vmware_host_datastore-resignature_vvols.yaml
  plugins/modules/vmware_host_datastore.py
Labels: feature, mergeit
