Repository ansible-collections/community.vmware, pull requests merged in 2023-05, with the labels that each got.

#1727 2.x: Pin vsphere-automation-sdk to v8.0.0.0
  changelogs/fragments/1715-requirements.yml
  requirements.txt
Labels: bug, has_issue, mergeit

#1738 prepare 3.6.0 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1706-vmware_vsan_health_info.yml
  changelogs/fragments/1713-vmware_guest-custom_attributes_on_create.yaml
  docs/community.vmware.vsan_health_silent_checks_module.rst
  galaxy.yml
Labels: mergeit

#1739 Remove version 3.6.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1705 docs(vmware_object_role_permission): Clarify vCenter compatibility
  plugins/modules/vmware_object_role_permission.py
  plugins/modules/vmware_object_role_permission_info.py
Labels: documentation, mergeit

#1743 vmware_guest_serial_port: add support for proxyURI parameter
  changelogs/fragments/1742-vmware_guest_serial_port-vspc.yml
  docs/community.vmware.vmware_guest_serial_port_module.rst
  plugins/modules/vmware_guest_serial_port.py
Labels: feature, has_issue, mergeit

#1745 [WIP] Fix test requirements
  tests/requirements.yml
  tox.ini
Labels: mergeit

#1702 add vmware_vsan_release_catalog module
  plugins/modules/vmware_vsan_release_catalog.py
Labels: new_module, mergeit

#1748 stable-2.x: Backport move some tests to GH Actions
  .github/workflows/ansible-test.yml
  .github/workflows/extra-docs-linting.yml
Labels: CI, mergeit

#1750 stable-2.x: Backport temporarily disable 2.15 sanity tests
  .github/workflows/ansible-test.yml
Labels: CI, mergeit

#1736 vmware_cluster_drs_recommendations - add a modul to apply the drs recommendations
  changelogs/fragments/1736-vmware_cluster_drs_recommendations.yaml
  plugins/modules/vmware_cluster_drs_recommendations.py
Labels: new_module, mergeit

#1754 CI: Remove unnecessary prepare step
  tests/integration/targets/prepare_vmware_tests/tasks/setup_datastore.yml
Labels: CI, mergeit

#1753 Fix 2.15 sanity tests
  .github/workflows/ansible-test.yml
  plugins/modules/vmware_portgroup.py
  plugins/modules/vmware_vswitch.py
Labels: CI, mergeit
