Repository ansible-collections/community.vmware, pull requests merged in 2023-06, with the labels that each got.

#1758 Backport 1753: Fix 2.15 sanity tests
  .github/workflows/ansible-test.yml
  plugins/modules/vmware_portgroup.py
  plugins/modules/vmware_vswitch.py
Labels: mergeit

#1763 backport 1757: Fix 2.15 integration test
  tests/integration/targets/vmware_vm_info/tasks/main.yml
Labels: CI, mergeit

#1710 add missing show_folder
  changelogs/fragments/1710_vmware_vm_info.yaml
  plugins/modules/vmware_vm_info.py
Labels: mergeit

#1762 Update vmware_vm_inventory.py
  plugins/inventory/vmware_vm_inventory.py
Labels: docs, mergeit

#1764 meta/runtime.yml: Add missing modules
  changelogs/fragments/1764_runtime.yaml
  meta/runtime.yml
Labels: bug, mergeit

#1768 Remove version 3.7.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1766 Do not fail when state is absent and disk is not found
  changelogs/fragments/1765_vmware_guest_disk.yaml
  plugins/modules/vmware_guest_disk.py
  tests/integration/targets/vmware_guest_disk/tasks/main.yml
Labels: bug, has_issue, mergeit

#1593 vmware_deploy_ovf: Fix an issue with non-supportet network-mappings (issues #164 and #1590)
  plugins/module_utils/vmware.py
  plugins/modules/vmware_deploy_ovf.py
Labels: bug, has_issue, mergeit

#1776 PR 1593: Add changelog fragment
  changelogs/fragments/1590_vmware_deploy_ovf.yaml
Labels: documentation, mergeit

#1775 Update vmware_host_scanhba.py
  plugins/modules/vmware_host_scanhba.py
Labels: documentation, mergeit

#1751 Also look at NFS mounted datastores, not just VMFS
  changelogs/fragments/1751-autoselect_datastore-also-use-NFS-mounts.yml
  plugins/modules/vmware_guest.py
Labels: mergeit

#1783 Ignore some sanity tests in 2.16
  tests/sanity/ignore-2.16.txt
Labels: mergeit

#1784 stable-2.x: Ignore some sanity tests in 2.16
  tests/sanity/ignore-2.16.txt
Labels: mergeit

#1774 Add VASA modules
  changelogs/fragments/1774_vmware_vasa.yaml
  changelogs/fragments/1774_vmware_vasa_info.yaml
  meta/runtime.yml
  plugins/module_utils/vmware_sms.py
  plugins/modules/vmware_vasa.py
  plugins/modules/vmware_vasa_info.py
Labels: new_module, mergeit
