Repository ansible-collections/community.vmware, pull requests merged in 2023-12, with the labels that each got.

#1941 Fix integration tests
  tests/integration/targets/vmware_about_info/tasks/main.yml
  tests/integration/targets/vmware_category/tasks/associable_obj_test.yml
  tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
  tests/integration/targets/vmware_folder_info/tasks/main.yml
  tests/integration/targets/vmware_guest_controller/tasks/main.yml
  tests/integration/targets/vmware_guest_network/tasks/main.yml
Labels: mergeit

#1943 stable-3.x: Fix integration tests
  tests/integration/targets/vmware_about_info/tasks/main.yml
  tests/integration/targets/vmware_category/tasks/associable_obj_test.yml
  tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
  tests/integration/targets/vmware_folder_info/tasks/main.yml
  tests/integration/targets/vmware_guest_controller/tasks/main.yml
  tests/integration/targets/vmware_guest_network/tasks/main.yml
Labels: mergeit

#1938 vmware_category: Improve documentation
  plugins/modules/vmware_category.py
Labels: mergeit

#1945 vmware_category: Improve documentation (#1938)
  plugins/modules/vmware_category.py
Labels: mergeit

#1953 [BUGFIX] Added the missing init for the rest client
  plugins/modules/vcenter_root_password_expiration.py
Labels: bug, mergeit

#1955 vcenter_root_password_expiration: Add integration test
  tests/integration/targets/vcenter_root_password_expiration/aliases
  tests/integration/targets/vcenter_root_password_expiration/tasks/main.yml
Labels: integration, mergeit
