Repository ansible-collections/community.vmware, pull requests merged in 2023-10, with the labels that each got.

#1847 Add snapshot_id option to vmware_guest_snapshot module
  changelogs/fragments/1847_vmware_guest_snapshot.yml
  docs/community.vmware.vmware_guest_snapshot_module.rst
  plugins/modules/vmware_guest_snapshot.py
  tests/integration/targets/vmware_guest_snapshot/tasks/main.yml
Labels: mergeit

#1859 4.0.0: Removing support for ansible-core version < 2.15.0
  .github/workflows/ansible-test.yml
  .github/workflows/extra-docs-linting.yml
  changelogs/fragments/4.0.0-required_ansible_version.yml
  meta/runtime.yml
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
Labels: mergeit

#1861 3.x: Update Readme for 4.0.0 release
  README.md
Labels: mergeit

#1855 vmware_dsv_portgroup_info: Add moid property in the return value and modify the return example
  changelogs/fragments/1855_ vmware_dsv_portgroup_info.yml
  docs/community.vmware.vmware_dvs_portgroup_info_module.rst
  plugins/modules/vmware_dvs_portgroup_info.py
Labels: mergeit

#1854 fix #1853
  changelogs/fragments/1853.yml
  plugins/modules/vmware_deploy_ovf.py
Labels: mergeit

#1846 fix issue #1772
  changelogs/fragments/issue_1772.yml
  plugins/modules/vmware_guest_custom_attributes.py
Labels: mergeit

#1863 3.x: vmware_dsv_portgroup_info: Add moid property in the return value
  changelogs/fragments/1855_ vmware_dsv_portgroup_info.yml
  docs/community.vmware.vmware_dvs_portgroup_info_module.rst
  plugins/modules/vmware_dvs_portgroup_info.py
Labels: mergeit

#1864 3.x: fix #1853
  changelogs/fragments/1853.yml
  plugins/modules/vmware_deploy_ovf.py
Labels: mergeit

#1865 3.x: fix issue #1772
  changelogs/fragments/issue_1772.yml
  plugins/modules/vmware_guest_custom_attributes.py
Labels: mergeit

#1867 prepare 3.10.0 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1847_vmware_guest_snapshot.yml
  changelogs/fragments/1853.yml
  changelogs/fragments/1855_ vmware_dsv_portgroup_info.yml
  changelogs/fragments/issue_1772.yml
  docs/community.vmware.vcenter_root_password_expiration_module.rst
  galaxy.yml
Labels: mergeit

#1868 Remove version 3.10.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1862 vmware_host_lockdown: Remove deprecated states absent and present
  changelogs/fragments/1517_vmware_host_lockdown.yml
  plugins/modules/vmware_host_lockdown.py
Labels: mergeit

#1870 Remove plugins/module_utils/version.py
  changelogs/fragments/1639.yml
  plugins/module_utils/version.py
  plugins/module_utils/vmware.py
  plugins/modules/vmware_category.py
  plugins/modules/vmware_vc_infraprofile_info.py
Labels: mergeit

#1871 vmware_vm_info: Add prefix length to IPs in vm_network
  changelogs/fragments/1761_vmware_vm_info.yml
  plugins/modules/vmware_vm_info.py
Labels: feature, has_issue, mergeit

#1874 stable-3.x: Configure SNMP for ESXi hosts via vCenter
  changelogs/fragments/1799_configure_snmp_on_esxii_hosts_via_vcenter.yaml
  docs/community.vmware.vmware_host_snmp_module.rst
  plugins/modules/vmware_host_snmp.py
  tests/integration/targets/vmware_host_snmp/aliases
  tests/integration/targets/vmware_host_snmp/tasks/main.yml
Labels: feature, has_issue, mergeit

#1883 vmware_deploy_ovf: Add new parameter enable_hidden_properties
  changelogs/fragments/802-vmware_deploy_ovf.yml
  plugins/modules/vmware_deploy_ovf.py
Labels: mergeit

#1884 Document 2.x as unmaintained
  README.md
Labels: mergeit

#1885 stable-3.x: Document 2.x as unmaintained
  README.md
Labels: mergeit

#1887 vmware_host_acceptance_info: Fix module doc
  plugins/modules/vmware_host_acceptance_info.py
Labels: mergeit

#1878 Implement semantic markup (1)
  plugins/doc_fragments/vmware.py
  plugins/doc_fragments/vmware_rest_client.py
Labels: documentation, mergeit

#1879 Implement semantic markup (2)
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_tools_connection.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  plugins/connection/vmware_tools.py
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
  tools/antsibull-docs-wrapper.sh
  tools/create_documentation_tasks.yml
Labels: documentation, mergeit

#1888 Implement semantic markup (4)
  docs/community.vmware.vmware_drs_group_info_module.rst
  docs/community.vmware.vmware_drs_group_manager_module.rst
  docs/community.vmware.vmware_drs_group_module.rst
  docs/community.vmware.vmware_drs_rule_info_module.rst
  docs/community.vmware.vmware_dvs_portgroup_find_module.rst
  docs/community.vmware.vmware_dvs_portgroup_module.rst
  docs/community.vmware.vmware_dvswitch_info_module.rst
  docs/community.vmware.vmware_dvswitch_lacp_module.rst
  docs/community.vmware.vmware_dvswitch_module.rst
  docs/community.vmware.vmware_dvswitch_nioc_module.rst
  docs/community.vmware.vmware_dvswitch_pvlans_module.rst
  docs/community.vmware.vmware_evc_mode_module.rst
  docs/community.vmware.vmware_export_ovf_module.rst
  docs/community.vmware.vmware_folder_info_module.rst
  docs/community.vmware.vmware_guest_boot_info_module.rst
  docs/community.vmware.vmware_guest_boot_manager_module.rst
  docs/community.vmware.vmware_guest_controller_module.rst
  docs/community.vmware.vmware_guest_cross_vc_clone_module.rst
  docs/community.vmware.vmware_guest_custom_attribute_defs_module.rst
  docs/community.vmware.vmware_guest_module.rst
  plugins/modules/vmware_drs_group.py
  plugins/modules/vmware_drs_group_info.py
  plugins/modules/vmware_drs_group_manager.py
  plugins/modules/vmware_drs_rule_info.py
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_dvs_portgroup_find.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_dvswitch_info.py
  plugins/modules/vmware_dvswitch_lacp.py
  plugins/modules/vmware_dvswitch_nioc.py
  plugins/modules/vmware_dvswitch_pvlans.py
  plugins/modules/vmware_evc_mode.py
  plugins/modules/vmware_export_ovf.py
  plugins/modules/vmware_folder_info.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_boot_info.py
  plugins/modules/vmware_guest_boot_manager.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_cross_vc_clone.py
  plugins/modules/vmware_guest_custom_attribute_defs.py
Labels: documentation, mergeit

#1890 Implement semantic markup (5)
  docs/community.vmware.vmware_guest_custom_attributes_module.rst
  docs/community.vmware.vmware_guest_disk_info_module.rst
  docs/community.vmware.vmware_guest_disk_module.rst
  docs/community.vmware.vmware_guest_file_operation_module.rst
  docs/community.vmware.vmware_guest_find_module.rst
  docs/community.vmware.vmware_guest_info_module.rst
  docs/community.vmware.vmware_guest_instant_clone_module.rst
  docs/community.vmware.vmware_guest_move_module.rst
  docs/community.vmware.vmware_guest_network_module.rst
  docs/community.vmware.vmware_guest_powerstate_module.rst
  docs/community.vmware.vmware_guest_register_operation_module.rst
  docs/community.vmware.vmware_guest_screenshot_module.rst
  docs/community.vmware.vmware_guest_sendkey_module.rst
  docs/community.vmware.vmware_guest_serial_port_module.rst
  docs/community.vmware.vmware_guest_snapshot_info_module.rst
  docs/community.vmware.vmware_guest_snapshot_module.rst
  docs/community.vmware.vmware_guest_storage_policy_module.rst
  docs/community.vmware.vmware_guest_tools_info_module.rst
  docs/community.vmware.vmware_guest_tools_upgrade_module.rst
  docs/community.vmware.vmware_guest_tools_wait_module.rst
  docs/community.vmware.vmware_guest_tpm_module.rst
  docs/community.vmware.vmware_guest_vgpu_info_module.rst
  docs/community.vmware.vmware_guest_vgpu_module.rst
  docs/community.vmware.vmware_guest_video_module.rst
  plugins/modules/vmware_guest_custom_attributes.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_disk_info.py
  plugins/modules/vmware_guest_file_operation.py
  plugins/modules/vmware_guest_find.py
  plugins/modules/vmware_guest_info.py
  plugins/modules/vmware_guest_instant_clone.py
  plugins/modules/vmware_guest_move.py
  plugins/modules/vmware_guest_network.py
  plugins/modules/vmware_guest_powerstate.py
  plugins/modules/vmware_guest_register_operation.py
  plugins/modules/vmware_guest_screenshot.py
  plugins/modules/vmware_guest_sendkey.py
  plugins/modules/vmware_guest_serial_port.py
  plugins/modules/vmware_guest_snapshot.py
  plugins/modules/vmware_guest_snapshot_info.py
  plugins/modules/vmware_guest_storage_policy.py
  plugins/modules/vmware_guest_tools_info.py
  plugins/modules/vmware_guest_tools_upgrade.py
  plugins/modules/vmware_guest_tools_wait.py
  plugins/modules/vmware_guest_tpm.py
  plugins/modules/vmware_guest_vgpu.py
  plugins/modules/vmware_guest_vgpu_info.py
  plugins/modules/vmware_guest_video.py
Labels: documentation, mergeit

#1894 Implement semantic markup (8)
  changelogs/fragments/1771-semantic_markup.yml
  docs/community.vmware.vmware_tag_manager_module.rst
  docs/community.vmware.vmware_tag_module.rst
  docs/community.vmware.vmware_target_canonical_info_module.rst
  docs/community.vmware.vmware_vasa_module.rst
  docs/community.vmware.vmware_vc_infraprofile_info_module.rst
  docs/community.vmware.vmware_vcenter_settings_info_module.rst
  docs/community.vmware.vmware_vcenter_settings_module.rst
  docs/community.vmware.vmware_vcenter_statistics_module.rst
  docs/community.vmware.vmware_vm_config_option_module.rst
  docs/community.vmware.vmware_vm_host_drs_rule_module.rst
  docs/community.vmware.vmware_vm_info_module.rst
  docs/community.vmware.vmware_vm_shell_module.rst
  docs/community.vmware.vmware_vm_storage_policy_module.rst
  docs/community.vmware.vmware_vm_vm_drs_rule_module.rst
  docs/community.vmware.vmware_vmkernel_info_module.rst
  docs/community.vmware.vmware_vmkernel_module.rst
  docs/community.vmware.vmware_vmotion_module.rst
  docs/community.vmware.vmware_vsan_health_info_module.rst
  docs/community.vmware.vmware_vspan_session_module.rst
  docs/community.vmware.vmware_vswitch_info_module.rst
  docs/community.vmware.vmware_vswitch_module.rst
  docs/community.vmware.vsan_health_silent_checks_module.rst
  docs/community.vmware.vsphere_file_module.rst
  plugins/modules/vmware_tag.py
  plugins/modules/vmware_tag_manager.py
  plugins/modules/vmware_target_canonical_info.py
  plugins/modules/vmware_vasa.py
  plugins/modules/vmware_vc_infraprofile_info.py
  plugins/modules/vmware_vcenter_settings.py
  plugins/modules/vmware_vcenter_settings_info.py
  plugins/modules/vmware_vcenter_statistics.py
  plugins/modules/vmware_vm_config_option.py
  plugins/modules/vmware_vm_host_drs_rule.py
  plugins/modules/vmware_vm_info.py
  plugins/modules/vmware_vm_shell.py
  plugins/modules/vmware_vm_storage_policy.py
  plugins/modules/vmware_vm_vm_drs_rule.py
  plugins/modules/vmware_vmkernel.py
  plugins/modules/vmware_vmkernel_info.py
  plugins/modules/vmware_vmotion.py
  plugins/modules/vmware_vsan_health_info.py
  plugins/modules/vmware_vspan_session.py
  plugins/modules/vmware_vswitch.py
  plugins/modules/vmware_vswitch_info.py
  plugins/modules/vsan_health_silent_checks.py
  plugins/modules/vsphere_file.py
Labels: documentation, mergeit

#1896 Implement semantic markup (9)
  docs/community.vmware.vmware_datastore_cluster_manager_module.rst
  docs/community.vmware.vmware_datastore_cluster_module.rst
  docs/community.vmware.vmware_datastore_info_module.rst
  docs/community.vmware.vmware_datastore_module.rst
  plugins/modules/vmware_datastore.py
  plugins/modules/vmware_datastore_cluster.py
  plugins/modules/vmware_datastore_cluster_manager.py
  plugins/modules/vmware_datastore_info.py
Labels: documentation, mergeit

#1897 Remove module docs from repo
  README.md
  changelogs/fragments/20231026-remove_module_docs.yml
  docs/community.vmware.vcenter_extension_info_module.rst
  docs/community.vmware.vmware_about_info_module.rst
  docs/community.vmware.vmware_category_info_module.rst
  docs/community.vmware.vmware_cluster_drs_recommendations_module.rst
  docs/community.vmware.vmware_cluster_vcls_module.rst
  docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
  docs/community.vmware.vmware_content_library_info_module.rst
  docs/community.vmware.vmware_datacenter_module.rst
  docs/community.vmware.vmware_dvs_host_module.rst
  docs/community.vmware.vmware_dvs_portgroup_info_module.rst
  docs/community.vmware.vmware_dvswitch_uplink_pg_module.rst
  docs/community.vmware.vmware_first_class_disk_module.rst
  docs/community.vmware.vmware_guest_customization_info_module.rst
  docs/community.vmware.vmware_host_iscsi_info_module.rst
  docs/community.vmware.vmware_host_logbundle_info_module.rst
  docs/community.vmware.vmware_host_logbundle_module.rst
  docs/community.vmware.vmware_host_scanhba_module.rst
  docs/community.vmware.vmware_host_tcpip_stacks_module.rst
  docs/community.vmware.vmware_httpapi.rst
  docs/community.vmware.vmware_local_role_info_module.rst
  docs/community.vmware.vmware_local_user_info_module.rst
  docs/community.vmware.vmware_migrate_vmk_module.rst
  docs/community.vmware.vmware_recommended_datastore_module.rst
  docs/community.vmware.vmware_resource_pool_info_module.rst
  docs/community.vmware.vmware_tag_info_module.rst
  docs/community.vmware.vmware_vasa_info_module.rst
  docs/community.vmware.vmware_vm_storage_policy_info_module.rst
  docs/community.vmware.vmware_vm_vss_dvs_migrate_module.rst
  docs/community.vmware.vmware_vsan_cluster_module.rst
  docs/community.vmware.vmware_vsan_hcl_db_module.rst
  docs/community.vmware.vmware_vsan_release_catalog_module.rst
  docs/community.vmware.vsphere_copy_module.rst
  tools/antsibull-docs-wrapper.sh
  tools/create_documentation_tasks.yml
  tools/prepare_release.yml
  tools/update_documentation.yml
Labels: documentation, mergeit

#1899 Module util vmware_rest_client: Remove get_tag_by_category
  changelogs/fragments/1898-vmware_rest_client.yml
  plugins/module_utils/vmware_rest_client.py
Labels: mergeit

#1900 Improve changelog fragments for 4.0.0
  README.md
  changelogs/fragments/1472-vmware_guest.yml
  changelogs/fragments/1517_vmware_host_lockdown.yml
  changelogs/fragments/1639.yml
  changelogs/fragments/1761_vmware_vm_info.yml
  changelogs/fragments/1799_configure_snmp_on_esxii_hosts_via_vcenter.yaml
  changelogs/fragments/1847_vmware_guest_snapshot.yml
  changelogs/fragments/1853.yml
  changelogs/fragments/1855_ vmware_dsv_portgroup_info.yml
  changelogs/fragments/1855_vmware_dsv_portgroup_info.yml
  changelogs/fragments/1872-vmware_host_acceptance.yml
  changelogs/fragments/1898-vmware_rest_client.yml
  changelogs/fragments/802-vmware_deploy_ovf.yml
  changelogs/fragments/issue_1772.yml
Labels: mergeit

#1902 Automatically remove changelog fragments
  changelogs/config.yaml
  tools/prepare_release.yml
Labels: mergeit

#1901 Remove version_added: 2.x
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_export_ovf.py
  plugins/modules/vmware_guest_instant_clone.py
  plugins/modules/vmware_guest_vgpu.py
  plugins/modules/vmware_host_iscsi_info.py
  plugins/modules/vmware_host_user_manager.py
  plugins/modules/vmware_migrate_vmk.py
  plugins/modules/vmware_object_role_permission.py
  plugins/modules/vmware_tag_manager.py
  plugins/modules/vmware_vm_info.py
  plugins/modules/vmware_vmotion.py
  plugins/modules/vmware_vswitch.py
  plugins/modules/vmware_vswitch_info.py
Labels: mergeit

#1907 stable-3.x: Fix ansible-tox-linters
  tox.ini
Labels: tests, mergeit

#1904 vmware_dvs_host: Defaults for vmnics and lag_uplinks
  changelogs/fragments/1516-vmware_dvs_host.yml
  plugins/modules/vmware_dvs_host.py
  tox.ini
Labels: feature, has_issue, mergeit

#1909 Prepare 4.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1472-vmware_guest.yml
  changelogs/fragments/1516-vmware_dvs_host.yml
  changelogs/fragments/1517_vmware_host_lockdown.yml
  changelogs/fragments/1639.yml
  changelogs/fragments/1761_vmware_vm_info.yml
  changelogs/fragments/1771-semantic_markup.yml
  changelogs/fragments/1799_configure_snmp_on_esxii_hosts_via_vcenter.yaml
  changelogs/fragments/1847_vmware_guest_snapshot.yml
  changelogs/fragments/1853.yml
  changelogs/fragments/1855_vmware_dsv_portgroup_info.yml
  changelogs/fragments/1872-vmware_host_acceptance.yml
  changelogs/fragments/1898-vmware_rest_client.yml
  changelogs/fragments/20231026-remove_module_docs.yml
  changelogs/fragments/4.0.0-required_ansible_version.yml
  changelogs/fragments/802-vmware_deploy_ovf.yml
  changelogs/fragments/issue_1772.yml
  galaxy.yml
Labels: mergeit

#1910 Remove version 4.0.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1911 prepare 3.11.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1799_configure_snmp_on_esxii_hosts_via_vcenter.yaml
  changelogs/fragments/802-vmware_deploy_ovf.yml
  docs/community.vmware.vmware_deploy_ovf_module.rst
  docs/community.vmware.vmware_host_snmp_module.rst
  galaxy.yml
Labels: mergeit

#1913 Prepare 3.11.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  galaxy.yml
Labels: mergeit

#1914 Remove version 3.11.1 from galaxy.yml
  galaxy.yml
Labels: mergeit
