Repository ansible-collections/community.vmware, pull requests merged in 2023-08, with the labels that each got.

#1824 Clean up unit test compatibility code, and fix unit tests for Python 3.12
  tests/unit/compat/__init__.py
  tests/unit/compat/mock.py
  tests/unit/compat/unittest.py
  tests/unit/mock/path.py
  tests/unit/mock/procenv.py
  tests/unit/module_utils/test_vmware.py
  tests/unit/modules/cloud/vmware/test_vmware_host_sriov.py
  tests/unit/modules/utils.py
Labels: python3, community_review, tests, mergeit

#1803 add url deploy feature
  .gitignore
  README.md
  docs/community.vmware.vmware_deploy_ovf_module.rst
  plugins/modules/vmware_deploy_ovf.py
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
Labels: mergeit

#1825 vmware_deploy_ovf: Fix sanity tests
  plugins/modules/vmware_deploy_ovf.py
Labels: mergeit

#1826 prepare 3.9.0 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1069_vmware_guest.yml
  changelogs/fragments/1777-vmware_host_datastore-resignature_vvols.yaml
  changelogs/fragments/1805_vmware_vm_info.yml
  docs/community.vmware.vmware_deploy_ovf_module.rst
  docs/community.vmware.vmware_dvswitch_uplink_pg_module.rst
  docs/community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_host_datastore_module.rst
  galaxy.yml
Labels: community_review, docs, mergeit

#1827 Remove version 3.9.0 from galaxy.yml
  galaxy.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1806 Vmware host graphics
  README.md
  docs/community.vmware.vmware_host_graphics_module.rst
  plugins/modules/vmware_host_graphics.py
Labels: new_module, mergeit
