Repository ansible-collections/community.vmware, pull requests merged in 2023-04, with the labels that each got.

#1697 vmware_host_service_manager: Enable integration tests again
  tests/integration/targets/vmware_host_service_manager/aliases
Labels: CI, tests, mergeit

#1713 vmware_guest - set custom attributes on VM create
  changelogs/1713-vmware_guest-custom_attributes_on_create.yaml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#1714 Update community.vmware.vmware_guest_module.rst
  docs/community.vmware.vmware_guest_module.rst
  plugins/modules/vmware_guest.py
Labels: documentation, mergeit

#1717 PR 1713: Move changelog fragment to appropriate directory
  changelogs/fragments/1713-vmware_guest-custom_attributes_on_create.yaml
Labels: mergeit

#1706 fix(vmware_vsan_health_info): Return dict instead of JSON string
  changelogs/fragments/1706-vmware_vsan_health_info.yml
  plugins/modules/vmware_vsan_health_info.py
Labels: bug, mergeit
