Repository ansible-collections/community.vmware, pull requests merged in 2023-01, with the labels that each got.

#1583 Add module vmware_guest_vgpu_info
  plugins/modules/vmware_guest_vgpu_info.py
Labels: feature, has_issue, mergeit

#1589 meta/runtime.yml fixes
  meta/runtime.yml
Labels: bug, community_review, mergeit

#1584 vmware_tools: Fix an issue with pyVmomi 8.0.0.1
  changelogs/fragments/1578-vmware_tools-pyvmomi_8_0_0_1.yml
  plugins/connection/vmware_tools.py
Labels: bug, community_review, connection, has_issue, cloud, plugins, mergeit

#1591 [BACKPORT] vmware_tools: Fix an issue with pyVmomi 8.0.0.1
  changelogs/fragments/1578-vmware_tools-pyvmomi_8_0_0_1.yml
  plugins/connection/vmware_tools.py
Labels: bug, community_review, connection, cloud, plugins, mergeit

#1579 vmware_guest_network: add support pvrdma network adapter
  changelogs/fragments/1579-vmware_guest_network.yml
  plugins/module_utils/vm_device_helper.py
  plugins/modules/vmware_guest_network.py
  tests/integration/targets/vmware_guest_network/tasks/main.yml
Labels: feature, mergeit

#1598 prepare 2.10.3 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1578-vmware_tools-pyvmomi_8_0_0_1.yml
  galaxy.yml
  tox.ini
Labels: needs_info, needs_template, mergeit

#1599 Remove version 3.3.0 from galaxy.yml
  galaxy.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1600 Remove version 2.10.3 from galaxy.yml
  galaxy.yml
Labels: needs_info, needs_template, small_patch, mergeit

#1611 Fix broken references in scenario guides
  changelogs/fragments/1610-scenario_guides.yml
  docs/docsite/rst/vmware_scenarios/vmware_inventory_filters.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory_hostnames.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory_vm_attributes.rst
Labels: bug, community_review, has_issue, docs, mergeit

#1613 Fix broken references in scenario guides (#1611)
  changelogs/fragments/1610-scenario_guides.yml
  docs/docsite/rst/vmware_scenarios/vmware_inventory_filters.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory_hostnames.rst
  docs/docsite/rst/vmware_scenarios/vmware_inventory_vm_attributes.rst
Labels: bug, community_review, docs, mergeit
