Repository ansible-collections/community.vmware, pull requests merged in 2024-07, with the labels that each got.

#2114 prepare 4.5.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
  changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
  changelogs/fragments/2090-vmware_host_logbundle.yml
  changelogs/fragments/2092-vmware_host_logbundle.yml
  galaxy.yml
Labels: mergeit

#2115 Prepare 3.11.5 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
  changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
  docs/community.vmware.vcenter_folder_module.rst
  galaxy.yml
Labels: mergeit

#2116 Remove version 4.5.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2112 vsphere_file: Fix examples
  changelogs/fragments/2110-vsphere_file.yml
  plugins/modules/vsphere_file.py
Labels: mergeit

#2117 Remove version 3.11.5 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2119 README.md: Update Communication section
  README.md
Labels: documentation, mergeit

#2095 vmware_guest_disk: round size to int
  changelogs/fragments/2095_bugfix_vmware_guest_disk_round_size_to_int.yml
  plugins/modules/vmware_guest_disk.py
Labels: mergeit

#2102 vmware_vm_vm_drs_rule: add datacenter argument
  changelogs/fragments/2102_vm_vm_drs_rule_datacenter_argument.yml
  plugins/modules/vmware_vm_vm_drs_rule.py
Labels: mergeit

#2122 README.md: Update vSAN SDK link which redirects
  README.md
Labels: documentation, docs, mergeit
