Repository ansible-collections/community.vmware, pull requests merged in 2024-11, with the labels that each got.

#2230 prepare 5.1.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
  changelogs/fragments/2194-vmware_vm_info.yml
  changelogs/fragments/2208-vmware_vmotion.yml
  changelogs/fragments/2217-deprecate-vmware_cluster_dpm.yml
  changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
  galaxy.yml
Labels: mergeit

#2231 Remove version 5.1.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2232 prepare 4.8.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
  changelogs/fragments/2194-vmware_vm_info.yml
  changelogs/fragments/2208-vmware_vmotion.yml
  changelogs/fragments/2217-deprecate-vmware_cluster_dpm.yml
  changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
  galaxy.yml
Labels: mergeit

#2233 Remove version 4.8.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2234 prepare 3.11.8 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
  changelogs/fragments/2208-vmware_vmotion.yml
  galaxy.yml
Labels: mergeit

#2235 Remove version 3.11.8 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2009 Fix disk creation resulting in 'invalid configuration for device' error
  changelogs/fragments/2009-fix-disk-add-failing-with-invalid-configuration-for-device.yml
  plugins/module_utils/vm_device_helper.py
Labels: bug, mergeit

#2010 Fix errors occuring during hardware version upgrade not being reported (fixes #2001)
  changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2249 stable-4.x: Fix hardware version upgrade errors not reported
  changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2243 vmware_guest_tools_upgrade: All possible tools status
  changelogs/fragments/2237-vmware_guest_tools_upgrade.yml
  plugins/modules/vmware_guest_tools_upgrade.py
Labels: bug, has_issue, mergeit

#2258 Temporarily disable integration test
  tests/integration/targets/inventory_vmware_host_inventory/playbook/test_options.yml
Labels: mergeit

#2254 stable-4.x: Fix vmware_guest idempotency whith dvswitch
  changelogs/fragments/2000-fix-vmware-guest-idempotency-with-dvswitch.yml
  plugins/modules/vmware_guest.py
  tests/integration/targets/inventory_vmware_host_inventory/playbook/test_options.yml
Labels: bug, mergeit

#2241 vmware_guest_info - Make "datacenter" property optional
  changelogs/fragments/2241-vmware_guest_info-make-datacenter-property-optional.yaml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_guest_info.py
  tests/integration/targets/vmware_vmotion/tasks/main.yml
Labels: mergeit

#2262 prepare 5.2.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2000-fix-vmware-guest-idempotency-with-dvswitch.yml
  changelogs/fragments/2009-fix-disk-add-failing-with-invalid-configuration-for-device.yml
  changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
  changelogs/fragments/2237-vmware_guest_tools_upgrade.yml
  changelogs/fragments/2241-vmware_guest_info-make-datacenter-property-optional.yaml
  galaxy.yml
Labels: mergeit

#2263 prepare 4.8.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2000-fix-vmware-guest-idempotency-with-dvswitch.yml
  changelogs/fragments/2009-fix-disk-add-failing-with-invalid-configuration-for-device.yml
  changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
  galaxy.yml
Labels: mergeit

#2264 Remove version 5.2.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2265 Remove version 4.8.1 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2260 Deprecate vmware_cluster_info
  .github/workflows/extra-docs-linting.yml
  changelogs/fragments/2260-deprecate-vmware_cluster_info.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_info.py
  tests/integration/targets/vmware_cluster_info/aliases
  tests/integration/targets/vmware_cluster_info/tasks/main.yml
Labels: mergeit
