Repository ansible-collections/community.vmware, pull requests merged in 2024-01, with the labels that each got.

#1957 Fix changelog
  changelogs/changelog.yaml
  changelogs/fragments/1937-vmware_guest.yml
Labels: documentation, mergeit

#1960 vmware_guest_sendkey: Add Windows key
  changelogs/fragments/1959-vmware_guest_sendkey.yml
  plugins/modules/vmware_guest_sendkey.py
Labels: feature, has_issue, mergeit

#1958 vmware_guest_tools_upgrade: New parameter installer_options
  changelogs/fragments/1059-vmware_guest_tools_upgrade.yml
  plugins/modules/vmware_guest_tools_upgrade.py
Labels: feature, has_issue, mergeit

#1966 Fixed broken link to development guideline
  testing.md
Labels: documentation, mergeit

#1969 Fix InsecureRequestWarning
  changelogs/fragments/1969-InsecureRequestWarning.yml
  plugins/module_utils/vmware_rest_client.py
Labels: bug, mergeit

#1970 stable-3.x: Fix InsecureRequestWarning for VmwareRestClient based modules
  changelogs/fragments/1969-InsecureRequestWarning.yml
  plugins/module_utils/vmware_rest_client.py
Labels: bug, module_utils, mergeit

#1975 Use shared workflow for Galaxy import test
  .github/workflows/import-galaxy.yml
Labels: CI, owner_pr, mergeit

#1967 Issue #1930 Replaced for code based on ssl.get_server_certificate().
  changelogs/fragments/1930-fix_ssl_deprecation_function.yml
  plugins/module_utils/vmware.py
Labels: bug, has_issue, mergeit

#1848 Fix failure of vm reconfiguration with enabled virt_based_security
  changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#1981 Fix PR 1848 changelog
  changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
Labels: documentation, mergeit

#1980 stable-3.x: Fix failure of vm reconfiguration with enabled virt_based_security
  changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#1983 Prepare 4.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1059-vmware_guest_tools_upgrade.yml
  changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
  changelogs/fragments/1930-fix_ssl_deprecation_function.yml
  changelogs/fragments/1937-vmware_guest.yml
  changelogs/fragments/1959-vmware_guest_sendkey.yml
  changelogs/fragments/1969-InsecureRequestWarning.yml
  galaxy.yml
Labels: mergeit

#1984 Prepare 3.11.2 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
  changelogs/fragments/1969-InsecureRequestWarning.yml
  docs/community.vmware.vmware_category_module.rst
  docs/community.vmware.vmware_host_inventory_inventory.rst
  docs/community.vmware.vmware_vm_inventory_inventory.rst
  galaxy.yml
Labels: mergeit

#1985 Remove version 4.1.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#1986 Remove version 3.11.2 from galaxy.yml
  galaxy.yml
Labels: mergeit
