Repository ansible-collections/community.vmware, pull requests merged in 2024-05, with the labels that each got.

#2057 check if dpm config is None
  changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
  plugins/modules/vmware_cluster_dpm.py
Labels: bug, mergeit

#2058 check if dpm config is None
  changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
  plugins/modules/vmware_cluster_dpm.py
Labels: bug, mergeit

#2059 Backport vmware_dvs_portgroup: don't update on non-specified num_ports
  changelogs/fragments/2053-vmware_dvs_portgroup.yml
  plugins/modules/vmware_dvs_portgroup.py
Labels: bug, mergeit

#2065 Disable vmware_content_library_manager integration tests
  tests/integration/targets/vmware_content_library_manager/aliases
Labels: CI, mergeit

#2063 Prepare depending on vmware.vmware
  .github/workflows/ansible-test.yml
Labels: CI, mergeit

#2068 stable-3.x: Fix vmware_content_library_manager integration tests
  tests/integration/targets/vmware_content_library_manager/tasks/main.yml
Labels: CI, mergeit

#2071 Require pyVmomi 6.7.1
  changelogs/fragments/2071-clarify-pyvmomi-requirement.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_cluster_info.py
  plugins/modules/vmware_datacenter_info.py
  plugins/modules/vmware_datastore_info.py
  plugins/modules/vmware_dvswitch_info.py
  plugins/modules/vmware_guest_info.py
  plugins/modules/vmware_host_facts.py
  plugins/modules/vmware_vcenter_settings_info.py
  plugins/modules/vmware_vsan_health_info.py
  requirements.txt
Labels: mergeit

#2074 prepare 4.4.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2053-vmware_dvs_portgroup.yml
  changelogs/fragments/2055-vmware_dvs_portgroup-status_default.yml
  changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
  changelogs/fragments/2071-clarify-pyvmomi-requirement.yml
  galaxy.yml
Labels: mergeit

#2075 prepare 3.11.4 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2053-vmware_dvs_portgroup.yml
  changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
  galaxy.yml
Labels: mergeit

#2076 Remove version 4.4.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2077 Remove version 3.11.4 from galaxy.yml
  galaxy.yml
Labels: mergeit
