Repository ansible-collections/community.vmware, pull requests merged in 2024-02, with the labels that each got.

#1972 Add subproperties option to vmware_vm_inventory
  changelogs/fragments/1972-vm_inventory_subproperties.yml
  plugins/inventory/vmware_vm_inventory.py
Labels: feature, mergeit

#1994 vmware_host_facts - related datacenter
  changelogs/fragments/1994-vmware-host-facts.yml
  plugins/modules/vmware_host_facts.py
Labels: feature, mergeit

#1995 Add possiblity to tell vsphere_copy which diskformat is being uploaded
  changelogs/fragments/1995-vsphere_copy.yml
  plugins/modules/vsphere_copy.py
Labels: feature, mergeit

#1979 vmware_vmkernel - add enable_backup_nfc setting
  changelogs/fragments/1978-vmware_vmkernel.yaml
  plugins/modules/vmware_vmkernel.py
Labels: feature, mergeit

#2003 vmware_vmkernel: Add missing version_added
  plugins/modules/vmware_vmkernel.py
Labels: documentation, mergeit

#1996 vmware_first_class_disk_info - Add a module to gather infos about first class disks
  changelogs/fragments/1996 - vmware_first_class_disk_info.yml
  meta/runtime.yml
  plugins/module_utils/vmware.py
  plugins/modules/vmware_first_class_disk_info.py
  tests/integration/targets/vmware_first_class_disk_info/aliases
  tests/integration/targets/vmware_first_class_disk_info/tasks/main.yml
Labels: feature, integration, new_module, mergeit

#2005 vsphere_copy: make spelling of StreamVmdk consistent
  plugins/modules/vsphere_copy.py
Labels: bug, mergeit

#2007 prepare 4.2.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1972-vm_inventory_subproperties.yml
  changelogs/fragments/1977-vsphere_file_add_env_fallback.yml
  changelogs/fragments/1978-vmware_vmkernel.yaml
  changelogs/fragments/1994-vmware-host-facts.yml
  changelogs/fragments/1995-vsphere_copy.yml
  changelogs/fragments/1996 - vmware_first_class_disk_info.yml
  galaxy.yml
Labels: mergeit

#2008 Remove version 4.2.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2011 Fix Pylint errors in CI
  changelogs/fragments/2024027-fix_ci.yml
  plugins/module_utils/vmware.py
  scripts/inventory/vmware_inventory.py
  tests/unit/mock/loader.py
Labels: CI, mergeit

#2012 stable-3.x: Fix Pylint errors in CI
  changelogs/fragments/2024027-fix_ci.yml
  plugins/module_utils/vmware.py
  scripts/inventory/vmware_inventory.py
  tests/unit/mock/loader.py
Labels: CI, mergeit
