Repository ansible-collections/community.vmware, pull requests merged in 2024-04, with the labels that each got.

#2036 Missing an error message when guest_id is set while using template in…
  changelogs/fragments/2036-missing_error_msg_in_vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2039 Update CI
  .github/workflows/ansible-test.yml
  .github/workflows/extra-docs-linting.yml
Labels: CI, mergeit

#2037 Fix typos
  plugins/modules/vmware_guest.py
Labels: docs, mergeit

#2040 stable-3.x: Missing error msg in vmware_guest
  changelogs/fragments/2036-missing_error_msg_in_vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: bug, has_issue, has_pr, mergeit

#2042 Ignore some sanity tests in 2.18
  tests/sanity/ignore-2.18.txt
Labels: CI, mergeit

#2029 add vmware_all_snapshots_info new module
  meta/runtime.yml
  plugins/modules/vmware_all_snapshots_info.py
Labels: module, new_module, mergeit

#2034 vmware_guest_tools_info: Use toolsVersionStatus2
  changelogs/fragments/2033-vmware_guest_tools_info.yml
  plugins/modules/vmware_guest_tools_info.py
Labels: feature, has_issue, deprecated, mergeit

#2044 Fix update VM while adding a new disk
  changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2046 stable-3.x: Ignore some sanity tests in 2.18
  tests/sanity/ignore-2.18.txt
Labels: CI, mergeit

#2045 Fix update VM while adding a new disk (#2044)
  changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2018 vmware_vm_shell - improve doc ( folder var description )
  plugins/modules/vmware_vm_shell.py
Labels: documentation, mergeit

#1949 Add switchIpAddress to vmware_dvswitch module
  changelogs/fragments/1949-dvswitch_netflow_switch_ip.yml
  plugins/modules/vmware_dvswitch.py
Labels: feature, mergeit

#2048 prepare 4.3.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1949-dvswitch_netflow_switch_ip.yml
  changelogs/fragments/2019-doc_fragments-case-sensitive.yml
  changelogs/fragments/2022-drop_sceanrio_guides.yml
  changelogs/fragments/2024027-fix_ci.yml
  changelogs/fragments/2033-vmware_guest_tools_info.yml
  changelogs/fragments/2036-missing_error_msg_in_vmware_guest.yml
  changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
  galaxy.yml
Labels: mergeit

#2049 prepare 3.11.3 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2022-drop_sceanrio_guides.yml
  changelogs/fragments/2024027-fix_ci.yml
  changelogs/fragments/2036-missing_error_msg_in_vmware_guest.yml
  changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
  galaxy.yml
Labels: mergeit

#2050 Remove version 4.3.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2051 Remove version 3.11.3 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2055 vmware_dvs_portgroup: Make status present the default
  changelogs/fragments/2055-vmware_dvs_portgroup-status_default.yml
  plugins/modules/vmware_dvs_portgroup.py
Labels: feature, mergeit

#2053 vmware_dvs_portgroup: don't update on non-specified num_ports
  changelogs/fragments/2053-vmware_dvs_portgroup.yml
  plugins/modules/vmware_dvs_portgroup.py
  tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
Labels: bug, mergeit
