Repository ansible-collections/community.vmware, pull requests merged in 2024-08, with the labels that each got.

#2128 Document requirement on requests
  README.md
  changelogs/fragments/2127-require-requests.yml
  requirements.txt
Labels: bug, mergeit

#2130 README: Add forum group
  README.md
Labels: documentation, mergeit

#2132 stable-3.x: README.md: Update Communication section
  README.md
Labels: documentation, mergeit

#2133 stable-3.x: README.md: Update vSAN SDK link which redirects
  README.md
Labels: documentation, docs, mergeit

#2131 stable-3.x: vmware_guest_disk: round size to int
  changelogs/fragments/2095_bugfix_vmware_guest_disk_round_size_to_int.yml
  plugins/modules/vmware_guest_disk.py
Labels: bug, mergeit

#2134 stable-3.x: Document requirement on requests
  README.md
  changelogs/fragments/2127-require-requests.yml
  requirements.txt
Labels: bug, mergeit

#2135 stable-3.x: README: Add forum group
  README.md
Labels: documentation, mergeit

#2140 Temporarily disable runtime-metadata sanity test
  .github/workflows/ansible-test.yml
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
Labels: CI, mergeit

#2136 Deprecate vmware_cluster_drs
  changelogs/fragments/2136-deprecate-vmware_cluster_drs.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_drs.py
Labels: mergeit

#2141 Switch back to milestone instead of devel
  .github/workflows/ansible-test.yml
  tests/sanity/ignore-2.18.txt
Labels: CI, mergeit

#2129 Fixed naming of vm_info variable for consistency.
  plugins/modules/vmware_vm_info.py
Labels: documentation, mergeit
