Repository ansible-collections/community.vmware, pull requests merged in 2024-06, with the labels that each got.

#2080 avoid attribute error on allowedDatastores
  changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
  plugins/modules/vmware_cluster_vcls.py
Labels: bug, mergeit

#2085 add module to check for VMs with Storage DRS Overrides on given datastore clusters
  plugins/modules/vmware_sdrs_vm_overrides_info.py
Labels: mergeit

#2088 vcenter_folder - remove bad documentation
  changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
  plugins/modules/vcenter_folder.py
Labels: mergeit

#2093 stable-3.x: avoid attribute error on allowedDatastores
  changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
  plugins/modules/vmware_cluster_vcls.py
Labels: bug, mergeit

#2094 stable-3.x: vcenter_folder - remove bad documentation
  changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
  plugins/modules/vcenter_folder.py
Labels: documentation, mergeit

#2092 vmware_host_logbundle: Add timeout
  changelogs/fragments/2092-vmware_host_logbundle.yml
  plugins/modules/vmware_host_logbundle.py
  tests/integration/targets/vmware_host_logbundle/tasks/main.yml
Labels: feature, mergeit
