Repository ansible-collections/community.vmware, pull requests merged in 2024-10, with the labels that each got.

#2192 Fix documentation
  .github/workflows/extra-docs-linting.yml
  changelogs/fragments/2192-fix-documentation.yml
  plugins/connection/vmware_tools.py
  plugins/modules/vcenter_standard_key_provider.py
  plugins/modules/vmware_dvswitch_nioc.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_serial_port.py
Labels: documentation, mergeit

#2193 stable-4.x: Fix documentation
  .github/workflows/extra-docs-linting.yml
  changelogs/fragments/2192-fix-documentation.yml
  plugins/connection/vmware_tools.py
  plugins/modules/vcenter_standard_key_provider.py
  plugins/modules/vmware_dvswitch_nioc.py
  plugins/modules/vmware_guest.py
  plugins/modules/vmware_guest_controller.py
  plugins/modules/vmware_guest_disk.py
  plugins/modules/vmware_guest_serial_port.py
Labels: documentation, mergeit

#2196 prepare 5.0.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2186-fix-sanity-tests.yml
  changelogs/fragments/2192-fix-documentation.yml
  galaxy.yml
Labels: mergeit

#2198 prepare 3.11.7 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2186-fix-sanity-tests.yml
  galaxy.yml
Labels: mergeit

#2199 Remove version 5.0.1 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2200 Remove version 4.7.1 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2201 Remove version 3.11.7 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2194 Update vmware_vm_info.py
  changelogs/fragments/2194-vmware_vm_info.yml
  plugins/modules/vmware_vm_info.py
Labels: mergeit

#2202 stable-4.x: Improve vmware_vm_info performance
  changelogs/fragments/2194-vmware_vm_info.yml
  plugins/modules/vmware_vm_info.py
Labels: mergeit

#2203 Correct minor typo "vminfo" to "vm_info"
  plugins/modules/vmware_vm_info.py
Labels: documentation, mergeit

#2208 vmware_vmotion: Catch no placement recommendation
  changelogs/fragments/2208-vmware_vmotion.yml
  plugins/modules/vmware_vmotion.py
Labels: bug, has_issue, mergeit

#2209 Fix changelog entry
  changelogs/fragments/2208-vmware_vmotion.yml
Labels: mergeit

#2212 Document 3.x as unmaintained
  README.md
Labels: mergeit

#2210 stable-4.x: vmware_vmotion: Catch no placement recommendation
  changelogs/fragments/2208-vmware_vmotion.yml
  plugins/modules/vmware_vmotion.py
Labels: mergeit

#2211 stable-3.x: vmware_vmotion: Catch no placement recommendation
  changelogs/fragments/2208-vmware_vmotion.yml
  plugins/modules/vmware_vmotion.py
Labels: mergeit

#2213 stable-4.x: Document 3.x as unmaintained
  README.md
Labels: mergeit

#2214 stable-3.x: Document 3.x as unmaintained
  README.md
Labels: mergeit

#2219 Install vmware.vmware for docs linting
  .github/workflows/extra-docs-linting.yml
Labels: mergeit

#2221 Install vmware.vmware>=1.6.0 for docs linting
  .github/workflows/extra-docs-linting.yml
Labels: mergeit

#2222 Install vmware.vmware>=1.6.0 for docs linting (2)
  .github/workflows/extra-docs-linting.yml
Labels: mergeit

#2217 Deprecate vmware_cluster_dpm
  changelogs/fragments/2217-deprecate-vmware_cluster_dpm.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_dpm.py
  tests/integration/targets/vmware_cluster_dpm/aliases
  tests/integration/targets/vmware_cluster_dpm/tasks/main.yml
Labels: mergeit

#2218 Deprecate vmware_cluster_drs_recommendations
  changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_drs_recommendations.py
Labels: mergeit

#2224 stable-4.x: Deprecate vmware_cluster_dpm
  changelogs/fragments/2217-deprecate-vmware_cluster_dpm.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_dpm.py
  tests/integration/targets/vmware_cluster_dpm/aliases
  tests/integration/targets/vmware_cluster_dpm/tasks/main.yml
Labels: mergeit

#2225 stable-4.x: Deprecate vmware_cluster_drs_recommendations
  changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_drs_recommendations.py
Labels: mergeit

#2173 Fix existing disk erroneously being recreated when dealing with 8 or more disks
  changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2227 stable-4.x: vmware_guest: Fix issue with 8 or more disks
  changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2228 stable-3.x: vmware_guest: Fix issue with 8 or more disks
  changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit
