Repository ansible-collections/community.vmware, pull requests merged in 2024-09, with the labels that each got.

#2146 Document snapshot_id available for state=revert
  changelogs/fragments/2055-vmware_guest_snapshot.yml
  plugins/modules/vmware_guest_snapshot.py
Labels: documentation, mergeit

#2147 Enable runtime-metadata sanity test for 2.16 and 2.17 again
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
Labels: CI, mergeit

#2150 prepare 3.11.6 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2095_bugfix_vmware_guest_disk_round_size_to_int.yml
  changelogs/fragments/2127-require-requests.yml
  galaxy.yml
Labels: mergeit

#2151 Remove version 4.6.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2152 Remove version 3.11.6 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2153 5.0.0: Removing support for ansible-core version < 2.17.0
  .github/workflows/ansible-test.yml
  changelogs/fragments/5.0.0-required_ansible_version.yml
  meta/runtime.yml
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
Labels: mergeit

#2143 Deprecate vmware_cluster
  changelogs/fragments/2143-deprecate-vmware_cluster.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster.py
Labels: mergeit

#2156 Deprecate vmware_cluster_vcls
  changelogs/fragments/2156-deprecate-vmware_cluster_vcls.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_vcls.py
Labels: mergeit

#2154 Drop securityPolicyOverrideAllowed / security_override
  changelogs/fragments/1998-dvs_portgroup.yml
  plugins/modules/vmware_dvs_portgroup.py
  plugins/modules/vmware_dvs_portgroup_info.py
  tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
  tests/integration/targets/vmware_vspan_session/tasks/main.yml
Labels: mergeit

#2155 4.x: Deprecate vmware_cluster
  changelogs/fragments/2143-deprecate-vmware_cluster.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster.py
Labels: mergeit

#2160 4.x: Deprecate vmware_cluster_vcls
  changelogs/fragments/2156-deprecate-vmware_cluster_vcls.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_vcls.py
Labels: mergeit

#2161 prepare 4.7.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2143-deprecate-vmware_cluster.yml
  changelogs/fragments/2156-deprecate-vmware_cluster_vcls.yml
  galaxy.yml
Labels: mergeit

#2162 Remove version 4.7.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2159 Depend on vmware.vmware
  changelogs/fragments/2159-depend-on-vmware.vmware.yml
  galaxy.yml
Labels: mergeit

#2165 vmware_all_snapshots_info: Fix datacenter parameter being ignored
  changelogs/fragments/2138-vmware_all_snapshots_info.yml
  plugins/modules/vmware_all_snapshots_info.py
Labels: bug, mergeit

#2168 Stable-4.x: vmware_all_snapshots_info: Fix datacenter ignored
  changelogs/fragments/2138-vmware_all_snapshots_info.yml
  plugins/modules/vmware_all_snapshots_info.py
Labels: bug, mergeit

#2166 vmware_guest_tools_info: Remove vm_tools_install_status
  changelogs/fragments/2078-vmware_guest_tools_info.yml
  plugins/modules/vmware_guest_tools_info.py
  tests/integration/targets/vmware_guest_tools_info/tasks/main.yml
Labels: deprecated, mergeit

#2170 Update Readme for 5.0.0 release
  README.md
Labels: documentation, mergeit

#2172 stable-4.x: Update Readme for 5.0.0 release
  README.md
Labels: mergeit

#2169 Remove deprecated modules from tests
  tests/integration/targets/prepare_vmware_tests/tasks/setup_cluster.yml
  tests/integration/targets/vmware_cluster/aliases
  tests/integration/targets/vmware_cluster/tasks/main.yml
  tests/integration/targets/vmware_cluster_dpm/tasks/main.yml
  tests/integration/targets/vmware_cluster_drs/aliases
  tests/integration/targets/vmware_cluster_drs/tasks/main.yml
  tests/integration/targets/vmware_cluster_ha/tasks/main.yml
  tests/integration/targets/vmware_cluster_info/tasks/main.yml
  tests/integration/targets/vmware_cluster_vsan/tasks/main.yml
  tests/integration/targets/vmware_evc_mode/tasks/main.yml
Labels: mergeit

#2163 Update 5.0.0 dependencies
  README.md
  changelogs/fragments/5.0.0-requirements.yml
  requirements.txt
Labels: mergeit

#2175 Drop module_utils.vmware.run_command_in_guest
  changelogs/fragments/2175-drop-module_utils.vmware.run_command_in_guest.yml
  plugins/module_utils/vmware.py
Labels: mergeit

#2174 Drop using guest.toolsStatus
  changelogs/2174.yml
  plugins/modules/vmware_guest_tools_upgrade.py
  plugins/modules/vmware_vm_shell.py
Labels: mergeit

#2179 Truncate changelog for 5.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2143-deprecate-vmware_cluster.yml
  changelogs/fragments/2156-deprecate-vmware_cluster_vcls.yml
Labels: mergeit

#2180 prepare 5.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1998-dvs_portgroup.yml
  changelogs/fragments/2078-vmware_guest_tools_info.yml
  changelogs/fragments/2138-vmware_all_snapshots_info.yml
  changelogs/fragments/2159-depend-on-vmware.vmware.yml
  changelogs/fragments/2174.yml
  changelogs/fragments/2175-drop-module_utils.vmware.run_command_in_guest.yml
  changelogs/fragments/5.0.0-required_ansible_version.yml
  changelogs/fragments/5.0.0-requirements.yml
  galaxy.yml
Labels: mergeit

#2181 Remove version 5.0.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2188 stable-3.x: Fix sanity tests
  changelogs/fragments/2186-fix-sanity-tests.yml
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
  plugins/modules/vmware_dvswitch.py
  plugins/modules/vmware_dvswitch_pvlans.py
  plugins/modules/vmware_guest_tpm.py
  plugins/modules/vmware_host.py
  plugins/modules/vmware_host_dns.py
  plugins/modules/vmware_host_powerstate.py
  plugins/modules/vmware_vmotion.py
  tests/sanity/ignore-2.19.txt
Labels: bug, CI, mergeit
