Repository ansible-collections/community.vmware, pull requests merged in 2025-01, with the labels that each got.

#2220 vmware_guest: Fix vApp property handling
  changelogs/fragments/2220-vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: bug, mergeit

#2276 add new spec param #2275
  changelogs/fragments/2275-vm-ou-customization.yml
  plugins/modules/vmware_guest.py
Labels: feature, has_issue, mergeit

#2272 Update vmware_guest.py docs
  plugins/modules/vmware_guest.py
Labels: documentation, mergeit

#2286 stable-4.x: Deprecate vmware_cluster_info
  changelogs/fragments/2260-deprecate-vmware_cluster_info.yml
  meta/runtime.yml
  plugins/modules/vmware_cluster_info.py
  tests/integration/targets/vmware_cluster_info/aliases
  tests/integration/targets/vmware_cluster_info/tasks/main.yml
Labels: mergeit

#2267 vmware_dvswitch_pvlans: The VLAN ID type has been updated to be handled as an integer
  changelogs/fragments/2216-vmware_dvswitch_pvlans.yml
  plugins/modules/vmware_dvswitch_pvlans.py
Labels: mergeit

#2277 vmware_guest_network speedup module
  changelogs/fragments/2277-vmware_guest_network.yml
  plugins/modules/vmware_guest_network.py
Labels: mergeit

#2278 vmware_guest speedup module
  changelogs/fragments/2278-vmware_guest.yml
  plugins/modules/vmware_guest.py
Labels: mergeit

#2288 prepare 5.3.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2216-vmware_dvswitch_pvlans.yml
  changelogs/fragments/2220-vmware_guest.yml
  changelogs/fragments/2260-deprecate-vmware_cluster_info.yml
  changelogs/fragments/2275-vm-ou-customization.yml
  changelogs/fragments/2277-vmware_guest_network.yml
  changelogs/fragments/2278-vmware_guest.yml
  galaxy.yml
Labels: mergeit

#2289 prepare 4.8.2 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2260-deprecate-vmware_cluster_info.yml
  galaxy.yml
Labels: mergeit

#2290 Remove version 5.3.0 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2291 Remove version 4.8.2 from galaxy.yml
  galaxy.yml
Labels: mergeit

#2283 Deprecate inventory plugins
  .github/workflows/extra-docs-linting.yml
  changelogs/fragments/2283-deprecate-inventory-plugins.yml
  meta/runtime.yml
  plugins/connection/vmware_tools.py
  plugins/inventory/vmware_host_inventory.py
  plugins/inventory/vmware_vm_inventory.py
  tests/integration/targets/inventory_vmware_host_inventory/aliases
  tests/integration/targets/inventory_vmware_host_inventory/playbook/build_inventory.yml
  tests/integration/targets/inventory_vmware_host_inventory/playbook/build_inventory_with_cache.yml
  tests/integration/targets/inventory_vmware_host_inventory/playbook/build_inventory_without_cache.yml
  tests/integration/targets/inventory_vmware_host_inventory/playbook/install_dependencies.yml
  tests/integration/targets/inventory_vmware_host_inventory/playbook/prepare_vmware.yml
  tests/integration/targets/inventory_vmware_host_inventory/playbook/test_inventory_cache.yml
  tests/integration/targets/inventory_vmware_host_inventory/playbook/test_options.yml
  tests/integration/targets/inventory_vmware_host_inventory/playbook/test_vmware_host_inventory.yml
  tests/integration/targets/inventory_vmware_host_inventory/runme.sh
  tests/integration/targets/inventory_vmware_vm_inventory/aliases
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/build_inventory.yml
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/build_inventory_with_cache.yml
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/build_inventory_without_cache.yml
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/install_dependencies.yml
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/prepare_vmware.yml
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_inventory_cache.yml
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
  tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_vmware_vm_inventory.yml
  tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
  tests/integration/targets/vmware_vm_inventory/aliases
  tests/integration/targets/vmware_vm_inventory/ansible.cfg
  tests/integration/targets/vmware_vm_inventory/prepare_environment.yml
  tests/integration/targets/vmware_vm_inventory/runme.sh
  tests/integration/targets/vmware_vm_inventory/test_inventory.yml
Labels: mergeit

#2293 Deprecate vmware_maintenancemode
  changelogs/fragments/2293-deprecate-vmware_maintenancemode.yml
  galaxy.yml
  meta/runtime.yml
  plugins/modules/vmware_maintenancemode.py
  tests/integration/targets/prepare_vmware_tests/tasks/move_host_out_of_cluster.yml
  tests/integration/targets/prepare_vmware_tests/tasks/setup_attach_hosts.yml
  tests/integration/targets/vmware_host_auto_start/tasks/main.yml
  tests/integration/targets/vmware_maintenancemode/aliases
  tests/integration/targets/vmware_maintenancemode/tasks/main.yml
  tests/integration/targets/vmware_resource_pool/tasks/main.yml
  tests/integration/targets/vmware_vmotion/tasks/main.yml
Labels: mergeit
